#!/usr/bin/env python3
"""
NetHack-es: Traduce mensajes de combate y otros del código C.
Las cadenas con %s preservan el formato, se traduce el texto circundante.
"""

import polib, subprocess, re

PO_FILE = "po/combined-es.po"

# Traducciones principales
T = {
    # === COMBATE: impactos ===
    "hit your %s on the %s.": "golpeas tu %s contra %s.",
    "%s hit by a huge chunk of metal!": "¡%s golpeado por un enorme trozo de metal!",
    "%s%s is hit%s": "%s%s es golpeado%s",
    "%s hit %s with a thud!": "¡%s golpea a %s con un golpe sordo!",
    "hit %s with %s.": "golpeas a %s con %s.",
    "Splat!  You hit %s with %s %s egg%s!": "¡Zas!  Golpeas a %s con %s %s de huevo%s!",
    "%s divides as you hit it%s!": "¡%s se divide cuando lo golpeas%s!",
    "hit it.": "golpearlo.",
    "hit %s with %s egg%s.": "golpeas a %s con%s huevo de %s.",
    "hit.": "golpeas.",
    "hit (%d)": "golpe (%d)",
    "Hit!": "¡Golpe!",
    "Hits!": "¡Golpes!",
    # === COMBATE: fallos ===
    "miss %s.": "fallas a %s.",
    "miss it.": "fallas.",
    "miss.": "fallas.",
    "miss wildly and stumble forwards.": "fallas salvajemente y tropiezas hacia adelante.",
    "miss %s from behind.": "fallas a %s por detrás.",
    "miss wildly.": "fallas salvajemente.",
    "Misses!": "¡Fallas!",
    # === COMBATE: ataques ===
    "strike %s from behind!": "¡golpeas a %s por detrás!",
    "strike %s!": "¡golpeas a %s!",
    "attack %s.": "atacas a %s.",
    "attack %s from behind!": "¡atacas a %s por detrás!",
    "uselessly attack %s.": "atacas inútilmente a %s.",
    "back toward %s, hitting %s %s!": "retrocedes hacia %s, golpeando a %s %s!",
    "Splat!  %s is hit with %s egg!": "¡Zas!  %s es golpeado con huevo de %s!",
    "Splat!": "¡Zas!",
    "Whack!": "¡Zas!",
    "Wham!": "¡Pum!",
    "Bam!": "¡Bam!",
    "Thump!": "¡Zumba!",
    # === COMBATE: defensor ===
    "%s %s blocks your attack to %s head.": "%s %s bloquea tu ataque a la cabeza de %s.",
    "%s helmet blocks %s attack to %s head.": "el casco de %s bloquea el ataque de %s a la cabeza de %s.",
    "hit your %s with your bullwhip.": "golpeas tu %s con tu látigo.",
    # === COMBATE: monstruos atacan ===
    "%s claws itself out of the ground!": "¡%s se abre paso desde el suelo con sus garras!",
    "%s back toward %s, hitting %s %s!": "%s retrocede hacia %s, golpeando a %s %s!",
    "%s %s from your powerful strike!": "%s %s por tu poderoso golpe!",
    "divide as %s hits you!": "te divides cuando %s te golpea!",
    # === DAÑO / MUERTE ===
    "You take %d damage.": "Recibes %d de daño.",
    "%s takes %d damage.": "%s recibe %d de daño.",
    "You are killed.": "Has muerto.",
    "You are killed by %s!": "¡Has muerto por %s!",
    "%s is killed.": "%s ha muerto.",
    "%s is killed by %s!": "¡%s ha muerto por %s!",
    "killed by %s": "muerto por %s",
    "killed": "muerto",
    # === SENSACIONES ===
    "feel great!": "¡te sientes genial!",
    "feel good!": "¡te sientes bien!",
    "feel bad.": "te sientes mal.",
    "feel terrible.": "te sientes fatal.",
    "feel very strange.": "te sientes muy extraño.",
    "feel strange.": "te sientes extraño.",
    "feel normal.": "te sientes normal.",
    "feel %s.": "te sientes %s.",
    "feel very %s.": "te sientes muy %s.",
    "seem unaffected by it.": "pareces no afectado.",
    "seem unhurt.": "pareces ileso.",
    "seem %s.": "pareces %s.",
    # === COMIDA ===
    "That food is bad.": "Esa comida está mala.",
    "This tastes terrible.": "Esto sabe horrible.",
    "This tastes delicious.": "Esto sabe delicioso.",
    "This tastes like %s.": "Esto sabe a %s.",
    "This tastes bland.": "Esto sabe insípido.",
    "Delicious!": "¡Delicioso!",
    "Yuck!": "¡Puaj!",
    "eat %s.": "comes %s.",
    "eat it.": "lo comes.",
    # === PUERTAS ===
    "The door opens.": "La puerta se abre.",
    "The door closes.": "La puerta se cierra.",
    "The door is locked.": "La puerta está cerrada con llave.",
    "The door is unlocked.": "La puerta está abierta.",
    "open the door.": "abres la puerta.",
    "close the door.": "cierras la puerta.",
    "lock the door.": "cierras la puerta con llave.",
    "unlock the door.": "abres la puerta con llave.",
    "kick the door open!": "¡pateas la puerta para abrirla!",
    "The door resists!": "¡La puerta resiste!",
    "The door bursts open!": "¡La puerta se abre de golpe!",
    # === TRAMPAS ===
    "You trigger a trap!": "¡Activaste una trampa!",
    "You avoid a trap.": "Evitas una trampa.",
    "%s triggers a trap!": "¡%s activó una trampa!",
    "You fall into a pit!": "¡Caes en una fosa!",
    "%s falls into a pit!": "¡%s cae en una fosa!",
    "You are caught in a bear trap!": "¡Eres atrapado por una cepo!",
    "Poison gas!": "¡Gas venenoso!",
    "An arrow shoots at you!": "¡Una flecha te dispara!",
    # === TIENDAS ===
    "Hello, %s!  Care to buy anything?": "¡Hola, %s!  ¿Quieres comprar algo?",
    "Hello, %s!  Care to sell anything?": "¡Hola, %s!  ¿Quieres vender algo?",
    "Thank you for your patronage!": "¡Gracias por tu clientela!",
    "You stole %s!": "¡Robaste %s!",
    "You are accused of stealing!": "¡Te acusan de robar!",
    "The shopkeeper demands payment!": "¡El tendero exige el pago!",
    # === INVENTARIO ===
    "You have %s.": "Tienes %s.",
    "You have nothing.": "No tienes nada.",
    "pick up %s.": "recoges %s.",
    "drop %s.": "suelta %s.",
    "You can't carry that.": "No puedes cargar con eso.",
    "You can't carry %s.": "No puedes cargar con %s.",
    "Your inventory is full.": "Tu inventario está lleno.",
    # === LEER ===
    "read the %s.": "lees %s.",
    "You read %s.": "Lees %s.",
    "The scroll vanishes!": "¡El pergamino se desvanece!",
    "The spellbook glows!": "¡El libro de hechizos brilla!",
    # === MAGIA / VARITAS ===
    "zap %s.": "disparas %s.",
    "You zap %s with %s!": "¡Disparas %s con %s!",
    "%s is zapped by %s!": "¡%s es alcanzado por %s!",
    "Nothing happens.": "No ocurre nada.",
    # === RELIGIÓN ===
    "You pray to %s.": "Rezas a %s.",
    "You feel that %s is %s with you.": "Sientes que %s está %s contigo.",
    "Your prayer is answered!": "¡Tu oración fue respondida!",
    "Your prayer is not answered.": "Tu oración no fue respondida.",
    # === EQUIPO ===
    "wield %s.": "equipas %s.",
    "wear %s.": "te pones %s.",
    "remove %s.": "te quitas %s.",
    "take off %s.": "te quitas %s.",
    "You are now wearing %s.": "Ahora llevas puesto %s.",
    "You are now wielding %s.": "Ahora llevas equipado %s.",
    # === DORMIR / DESPERTAR ===
    "You fall asleep.": "Te quedas dormido.",
    "You wake up.": "Te despiertas.",
    "%s falls asleep.": "%s se queda dormido.",
    "%s wakes up.": "%s se despierta.",
    # === AGARRES / SUJECIONES ===
    "You are grabbed by %s!": "¡Eres agarrado por %s!",
    "%s is grabbed!": "¡%s es agarrado!",
    "You are held by %s!": "¡Eres sujetado por %s!",
    "You are released.": "Eres liberado.",
    # === COMANDOS ===
    "Do what?": "¿Hacer qué?",
    "I don't know how to %s!": "¡No sé cómo %s!",
    # === DIRECCIONES ===
    "north": "norte",
    "south": "sur",
    "east": "este",
    "west": "oeste",
    "northwest": "noroeste",
    "northeast": "noreste",
    "southwest": "suroeste",
    "southeast": "sureste",
    "up": "arriba",
    "down": "abajo",
    "left": "izquierda",
    "right": "derecha",
    # === EXCLAMACIONES ===
    "Oh!": "¡Oh!",
    "Ah!": "¡Ah!",
    "Huh?": "¿Eh?",
    "Wow!": "¡Vaya!",
    "Ouch!": "¡Ay!",
    "Great!": "¡Genial!",
    "Oops!": "¡Vaya!",
    # === PALABRAS SUELTAS ===
    "the": "el",
    "a": "un",
    "an": "un",
    "The": "El",
    "A": "Un",
    "in": "en",
    "on": "en",
    "at": "en",
    "to": "a",
    "from": "de",
    "with": "con",
    "for": "para",
    "by": "por",
    "of": "de",
    "is": "es",
    "are": "estás",
    "was": "era",
    "were": "estabas",
    "have": "tienes",
    "has": "tiene",
    "had": "tenía",
    "not": "no",
    "no": "no",
    "There's": "Hay",
    "There is": "Hay",
    "That's": "Eso es",
    "It's": "Es",
    "It is": "Es",
    "This is": "Esto es",
    "Some": "Algún",
    "Some ": "Algún ",
    "No ": "No ",
    "no ": "no ",
    "your": "tu",
    "your ": "tu ",
    "You're": "Eres",
    "You've": "Has",
    "Can't": "No puedes",
    "Cannot": "No puedes",
    "Don't": "No",
    "don't": "no",
    "Isn't": "No es",
    "Aren't": "No estás",
    "Thou": "Tú",
    "thou": "tú",
    "thy": "tu",
    "thine": "tuyo",
    "thee": "te",
    "art": "eres",
    "hast": "has",
    "Suddenly, ": "De repente, ",
    "Unfortunately, ": "Desafortunadamente, ",
    # === PREFIJOS ===
    "Seems ": "Parece ",
    "Try ": "Intenta ",
    "Tries ": "Intenta ",
    "Begins ": "Empieza ",
    "Starts ": "Comienza ",
    "Stops ": "Para ",
    "Continues ": "Continúa ",
    "Ceases ": "Cesa ",
    # === SUSTANTIVOS ===
    "something": "algo",
    "nothing": "nada",
    "everything": "todo",
    "Someone": "Alguien",
    "someone": "alguien",
    # === VERBOS ===
    "find": "encuentras",
    "found": "encontraste",
    "smell": "hueles",
    "smelled": "oliste",
    "sense": "sientes",
    "sensed": "sentiste",
    "notice": "notas",
    "noticed": "notaste",
    "try": "intentas",
    "tries": "intenta",
    "seem": "pareces",
    "seems": "parece",
    "begin": "empiezas",
    "begins": "empieza",
    "take": "tomas",
    "takes": "toma",
    "drop": "sueltas",
    "drops": "suelta",
    "fall": "caes",
    "falls": "cae",
    "give": "das",
    "gives": "da",
    "enter": "entras",
    "enters": "entra",
    "sit": "te sientas",
    "sits": "se sienta",
    "stand": "te levantas",
    "stands": "se levanta",
    "leave": "sales",
    "leaves": "sale",
    "move": "te mueves",
    "moves": "se mueve",
    "jump": "saltas",
    "jumps": "salta",
    "turn": "giras",
    "turns": "gira",
    "step": "avanzas",
    "steps": "avanza",
    "walk": "caminas",
    "walks": "camina",
    "run": "corres",
    "runs": "corre",
    "swim": "nadas",
    "swims": "nada",
    "fly": "vuelas",
    "flies": "vuela",
    "crawl": "te arrastras",
    "crawls": "se arrastra",
    "hide": "te escondes",
    "hides": "se esconde",
    "stop": "te paras",
    "stops": "se para",
    "wait": "esperas",
    "waits": "espera",
    "push": "empujas",
    "pulls": "tira",
    "pull": "tiras",
    "pushes": "empuja",
    "throw": "lanzas",
    "throws": "lanza",
    "catch": "atrapas",
    "catches": "atrapa",
}

po = polib.pofile(PO_FILE)
applied = 0
for entry in po:
    if entry.msgstr or not entry.msgid:
        continue
    is_c = any(ref[0].startswith("src/") for ref in entry.occurrences)
    if not is_c:
        continue
    if entry.msgid in T:
        entry.msgstr = T[entry.msgid]
        applied += 1

po.save(PO_FILE)

# Compilar y copiar
subprocess.run(["msgfmt", PO_FILE, "-o", "po/combined-es.mo"])
subprocess.run(
    ["cp", "po/combined-es.mo", "playground/locale/es/LC_MESSAGES/nethack.mo"]
)

print(f"Traducciones aplicadas: {applied}")
print(
    f"Pendientes C: {sum(1 for e in po if not e.msgstr and any(ref[0].startswith('src/') for ref in e.occurrences))}"
)
