#!/usr/bin/env python3
"""
NetHack-es: Traduce dat/epitaph.txt en po/es.po.
Epitafios de tumbas - humor, referencias culturales, chistes macabros.
"""

import polib

PO_FILE = "po/es.po"

# Latin phrases (keep in Latin)
LATIN = set(
    [
        "Audi Partem Alteram",
        "Auri sacra fames",
        "Auribus teneo lupum",
        "Dulce et decorum est pro patria mori",
        "Et in Arcadia ego",
        "Hodie mihi, cras tibi",
        "Res omnia mea culpa est",
        "Sum quod eris",
        "Tu quoque, Brute?",
        "Ex post fucto",
        "Obesa Cantavit",
        "A.S. ->",
        "<- A.S.",
    ]
)

# Names/pop culture references to keep as-is
KEEP = set(
    [
        "Elvis",
        "R2D2 -- Rest, Tin Piece",
        "Algernon",
        "Beetlejuice Beetlejuice Beetlejuice",
        "I'll be back!",
        "Goldilocks -- This casket is just right",
        "All's well that ends well",
    ]
)

TRANSLATIONS = {
    # Standard epitaphs
    "Rest in peace": "Descansa en paz",
    "R.I.P.": "D.E.P.",
    "Rest In Pieces": "Descansa en Pedazos",
    "Note -- there are NO valuable items in this grave": "Nota -- NO hay objetos de valor en esta tumba",
    "1994-1995. The Longest-Lived Hacker Ever": "1994-1995. El Hacker Más Longevo de la Historia",
    "The Grave of the Unknown Hacker": "La Tumba del Hacker Desconocido",
    "We weren't sure who this was, but we buried him here anyway": "No estábamos seguros de quién era, pero lo enterramos aquí de todas formas",
    "Sparky -- he was a very good dog": "Sparky -- fue un perro muy bueno",
    "Beware of Electric Third Rail": "Cuidado con el Tercer Rail Eléctrico",
    "Made in Taiwan": "Hecho en Taiwán",
    "Og friend. Og good dude. Og died. Og now food.": "Og amigo. Og buen tío. Og murió. Og ahora comida.",
    "Please don't dig me up.  I'm perfectly happy down here. -- Resident": "Por favor, no me desentierres.  Estoy perfectamente feliz aquí abajo. -- El Residente",
    "Postman, please note forwarding address: Gehennom, Asmodeus's Fortress, fifth lemure on the left": "Cartero, por favor nota la dirección de reenvío: Gehennom, Fortaleza de Asmodeo, quinto lémmur a la izquierda",
    "Look out below!": "¡Cuidado abajo!",
    "Go away!": "¡Vete!",
    "Go away!  I'm trying to take a nap in here!  Bloody adventurers...": "¡Vete!  Estoy intentando dormir la siesta aquí.  Malditos aventureros...",
    "Soon you'll join this fellow in hell! -- the Wizard of Yendor": "¡Pronto te unirás a este tipo en el infierno! -- El Mago de Yendor",
    "Be careful, or this could happen to you!": "Ten cuidado, ¡o esto podría pasarte a ti!",
    "Caution! This grave contains toxic waste": "Precaución! Esta tumba contiene residuos tóxicos",
    "Sum quod eris": "Sum quod eris",
    "Here lies an Atheist, all dressed up and no place to go": "Aquí yace un Ateo, todo vestido y sin sitio al que ir",
    "Here lies Ezekiel, age 102.  The good die young.": "Aquí yace Ezequiel, 102 años.  Los buenos mueren jóvenes.",
    "Here lies my wife: Here let her lie! Now she's at rest and so am I.": "Aquí yace mi esposa: ¡Aquí que yazga! Ahora ella descansa, y yo también.",
    "Here lies Johnny Yeast.  Pardon me for not rising.": "Aquí yace Juan Levadura.  Perdón por no levantarme.",
    "He always lied while on the earth and now he's lying in it": "Siempre mintió en la tierra y ahora yace en ella",
    "I made an ash of myself": "Hice cenizas de mí mismo",
    "Soon ripe.  Soon rotten.  Soon gone.  But not forgotten.": "Pronto maduro.  Pronto podrido.  Pronto ido.  Pero no olvidado.",
    "Here lies the body of Jonathan Blake.  Stepped on the gas instead of the brake.": "Aquí yace el cuerpo de Juan Blanco.  Pisó el acelerador en vez del freno.",
    "Here lies the body of John Round.  Lost at sea and never found.": "Aquí yace el cuerpo de Juan Redondo.  Perdido en el mar y nunca encontrado.",
    "Go away!  I'm trying to take a nap in here!  Bloody adventurers...": "¡Vete!  Estoy intentando dormir la siesta aquí.  Malditos aventureros...",
    # Funny epitaphs
    "Alas fair Death, 'twas missed in life - some peace and quiet from my wife": "Ay, bella Muerte, se me echaba de menos en vida - algo de paz y silencio de mi esposa",
    "Applaud, my friends, the comedy is finished.": "Aplaudid, amigos míos, la comedia ha terminado.",
    "At last... a nice long sleep.": "Por fin... un buen sueño largo.",
    "Basil, assaulted by bears": "Basilio, atacado por osos",
    "Burninated": "Carbonizado",
    "Confusion will be my epitaph": "La confusión será mi epitafio",
    "Do not open until Christmas": "No abrir hasta Navidad",
    "Don't be daft, they couldn't hit an elephant at this dist-": "No seas tonto, no podrían darle a un elefante a esta dist-",
    "Don't forget to stop and smell the roses": "No olvides detenerte a oler las rosas",
    "Don't let this happen to you!": "¡No dejes que esto te pase a ti!",
    "Fatty and skinny went to bed.  Fatty rolled over and skinny was dead.  Skinny Smith 1983-2000.": "Gordo y flaco se fueron a la cama.  Gordo se dio la vuelta y flaco estaba muerto.  Flaco Smith 1983-2000.",
    "Finally I am becoming stupider no more": "Por fin ya no me estoy volviendo más estúpido",
    "Follow me to hell": "Sígueme al infierno",
    "Gone fishin'": "Fui a pescar",
    "Good night, sweet prince: And flights of angels sing thee to thy rest!": "Buenas noches, dulce príncipe: ¡Y vuelos de ángeles te canten a tu descanso!",
    "Go Team Ant!": "¡Vamos Hormiga!",
    "Gone Underground For Good": "Ido al Subsuelo para Siempre",
    "He farmed his way here": "Granjeó su camino hasta aquí",
    "He waited too long": "Esperó demasiado",
    "Here lies Bob - decided to try an acid blob": "Aquí yace Bob - decidió probar un ácido",
    "Here lies Dudley, killed by another %&#@#& newt.": "Aquí yace Dudley, muerto por otro %&#@#& tritón.",
    "Here lies Gregg, choked on an egg": "Aquí yace Gregg, atragantado con un huevo",
    "Here lies Lies.  It's True.": "Aquí yace Mentiras.  Es Verdad.",
    "Here lies The Lady's maid, died of a Vorpal Blade": "Aquí yace la criada de la Dama, muerta por una Hoja Vorpal",
    "Here lies a programmer.  Killed by a fatal error.": "Aquí yace un programador.  Muerto por un error fatal.",
    "Here lies the left foot of Jack, killed by a land mine.  Let us know if you find any more of him": "Aquí yace el pie izquierdo de Jack, muerto por una mina terrestre.  Avísanos si encuentras más de él",
    "I took both pills!": "¡Me tomé las dos pastillas!",
    "I'd rather be sailing": "Prefiero estar navegando",
    "I'm gonna make it!": "¡Voy a lograrlo!",
    "I will survive!": "¡Sobreviviré!",
    "Killed by a black dragon -- This grave is empty": "Muerto por un dragón negro -- Esta tumba está vacía",
    "Let me out of here!": "¡Sácame de aquí!",
    "Lookin' good, Medusa.": "Se ve bien, Medusa.",
    "Mrs. Smith, choked on an apple.  She left behind grieving husband, daughter, and granddaughter.": "Sra. Smith, atragantada con una manzana.  Dejó atrás a su esposo, hija y nieta afligidos.",
    "No!  I don't want to see my damn conduct!": "¡No!  ¡No quiero ver mi maldita conducta!",
    "Nobody believed her when she said her feet were killing her": "Nadie le creyó cuando dijo que los pies la estaban matando",
    "On the whole, I'd rather be in Minetown": "En general, prefiero estar en Minetown",
    "On vacation": "De vacaciones",
    "One corpse, sans head": "Un cadáver, sin cabeza",
    "Oops.": "Vaya.",
    "Out to Lunch": "Fuera a comer",
    "SOLD": "VENDIDO",
    "Someone set us up the bomb!": "¡Alguien nos puso la bomba!",
    "Take my stuff, I don't need it anymore": "Coge mis cosas, ya no las necesito",
    "Taking a year dead for tax reasons": "Pasando un año muerto por razones fiscales",
    "The reports of my demise are completely accurate": "Los informes de mi fallecimiento son completamente precisos",
    "This was actually just a pit, but since there was a corpse, we filled it": "Esto era en realidad solo una fosa, pero como había un cadáver, la rellenamos",
    "This way to the crypt": "Por aquí a la cripta",
    "VACANCY": "VACANTE",
    "Welcome!": "¡Bienvenido!",
    "Wish you were here!": "¡Ojalá estuvieras aquí!",
    "Yea, it got me too": "Sí, a mí también me atrapó",
    "You should see the other guy": "Deberías ver al otro tipo",
    "(This space for sale)": "(Este espacio en venta)",
    "If a man's deeds do not outlive him, of what value is a mark in stone?": "Si los hechos de un hombre no le sobreviven, ¿qué valor tiene una marca en piedra?",
    "He died of the flux.": "Murió de disentería.",
    "Gone, but not forgiven": "Se fue, pero no perdonado",
    "Gone But Not Forgotten": "Se fue pero no olvidado",
    "Gone away owin' more than he could pay.": "Se fue debiendo más de lo que podía pagar.",
    # More epitaphs (batch)
    "...for famous men have the whole earth as their memorial": "...pues los hombres famosos tienen toda la tierra como su memorial",
    "...and they made me engrave my own headstone too!": "...¡y me hicieron grabar mi propia lápida también!",
    "...but the blood has stopped pumping and I am left to decay...": "...pero la sangre ha dejado de bombear y me han dejado pudrirme...",
    "A masochist is never satisfied.": "Un masoquista nunca está satisfecho.",
    "Ach, 'twas a wee monster in the loch": "Ay, era un monstruito en el lago",
    "Adapt.  Enjoy.  Survive.": "Adáptate.  Disfruta.  Sobrevive.",
    "Adventure, hah!  Excitement, hah!": "¿Aventura, ja? ¿Emoción, ja?",
    "After all, what are friends for...": "Después de todo, ¿para qué están los amigos...",
    "After this, nothing will shock me": "Después de esto, nada me sorprenderá",
    "After three days, fish and guests stink": "A los tres días, huelen el pescado y los invitados",
    "Age and treachery will always overcome youth and skill": "La edad y la traición siempre vencerán a la juventud y la habilidad",
    "Ageing is not so bad.  The real killer is when you stop.": "Envejecer no es tan malo.  Lo que realmente mata es cuando te detienes.",
    "Ain't I a stinker?": "¿A que soy un maula?",
    "All else failed...": "Todo lo demás falló...",
    "All hail RNG": "Alabado sea el RNG",
    "All right, we'll call it a draw!": "¡De acuerdo, lo llamamos empate!",
    "Alone at last!": "¡Por fin solo!",
    "Always attack a floating eye from behind!": "¡Ataca siempre a un ojo flotante por detrás!",
    "Am I having fun yet?": "¿Me estoy divirtiendo ya?",
    "And I can still crawl, I'm not dead yet!": "Y todavía puedo arrastrarme, ¡no estoy muerto aún!",
    "And all I wanted was a free lunch": "Y todo lo que quería era un almuerzo gratis",
    "And all of the signs were right there on your face": "Y todas las señales estaban justo en tu cara",
    "And don't give me that innocent look either!": "¡Y no me pongas esa cara de inocente tampoco!",
    "And everyone died.  Boo hoo hoo.": "Y todos murieron.  Bua, bua, bua.",
    "And here I go again...": "Y aquí voy de nuevo...",
    "And nobody cares until somebody famous dies...": "Y a nadie le importa hasta que alguien famoso muere...",
    "And so it ends?": "¿Y así termina?",
    "And so... it begins.": "Y así... comienza.",
    "And sometimes the bear eats you.": "Y a veces el oso te come a ti.",
    "And then 'e nailed me 'ead to the floor!": "¡Y entonces me clavó la cabeza al suelo!",
    "And they said it couldn't be done!": "¡Y decían que no se podía hacer!",
    "And what do I look like?  The living?": "¿Y qué parezco? ¿El vivo?",
    "And yes, it was ALL his fault!": "¡Y sí, fue TODO culpa suya!",
    "And you said it was pretty here...": "Y decías que era bonito aquí...",
    "Another lost soul": "Otra alma perdida",
    "Any day above ground is a good day!": "¡Cualquier día sobre la tierra es un buen día!",
    "Any more of this and I'll die of a stroke before I'm 30.": "Un poco más de esto y moriré de un infarto antes de los 30.",
    "Anybody seen my head?": "¿Alguien ha visto mi cabeza?",
    "Anyone for deathmatch?": "¿Alguien para un deathmatch?",
    "Anything for a change.": "Cualquier cosa por un cambio.",
    "Anything that kills you makes you ... well, dead": "Cualquier cosa que te mate te deja... bueno, muerto",
    "Anything worth doing is worth overdoing.": "Cualquier cosa que merezca la pena hacer merece la pena pasarse.",
    "Are unicorns supposedly peaceful if you're a virgin?  Hah!": "¿Se supone que los unicornios son pacíficos si eres virgen?  ¡Ja!",
    "Are we all being disintegrated, or is it just me?": "¿Nos están desintegrando a todos, o solo soy yo?",
    "At least I'm good at something": "Al menos soy bueno en algo",
    "Attempted suicide": "Intento de suicidio",
    "Be prepared": "Sé previsor",
    "Beauty survives": "La belleza sobrevive",
    "Been Here.  Now Gone.  Had a Good Time.": "Estuve Aquí.  Ahora Me Fui.  Lo Pasé Bien.",
    "Been through Hell, eh?  What did you bring me?": "Has estado en el Infierno, ¿eh?  ¿Qué me has traído?",
    "Beg your pardon, didn't recognize you, I've changed a lot.": "Perdona, no te reconocí, he cambiado mucho.",
    "Being dead builds character": "Estar muerto forja el carácter",
    "Beloved daughter, a treasure, buried here.": "Amada hija, un tesoro, enterrada aquí.",
    "Best friends come and go....  Mine just die.": "Los mejores amigos van y vienen....  Los míos solo mueren.",
    "Better be dead than a fat slave": "Mejor muerto que esclavo gordo",
    "Better luck next time": "Mejor suerte la próxima vez",
    "Beware of Discordians bearing answers": "Cuidado con los Discordianos que traen respuestas",
    "Beware the ...": "Cuidado con el ...",
    "Bloody Hell...": "Maldito Infierno...",
    "Bloody barbarians!": "¡Malditos bárbaros!",
    "Blown upward out of sight: He sought the leak by candlelight": "Voló hacia arriba fuera de vista: Buscó la fuga a la luz de una vela",
    "Brains... Brains... Fresh human brains...": "Cerebros... Cerebros... Cerebros humanos frescos...",
    "Buried the cat.  Took an hour.  Damn thing kept fighting.": "Enterré al gato.  Tardé una hora.  El maldito no dejaba de resistirse.",
    "But I disarmed the trap!": "¡Pero yo desactivé la trampa!",
    "Call me if you need my phone number!": "¡Llámame si necesitas mi número de teléfono!",
    "Can YOU fly?": "¿Puedes VOLAR?",
    "Can you believe that thing is STILL moving?": "¿Puedes creer que esa cosa SIGUE moviéndose?",
    "Can you come up with some better ending for this?": "¿Se te ocurre un final mejor para esto?",
    "Can you feel anything when I do this?": "¿Sientes algo cuando hago esto?",
    "Can you give me mouth to mouth, you just took my breath away.": "¿Puedes darme el boca a boca, me has dejado sin aliento.",
    "Can't I just have a LITTLE peril?": "¿No puedo tener aunque sea un POCO de peligro?",
    "Can't eat, can't sleep, had to bury the husband here.": "No puedo comer, no puedo dormir, tuve que enterrar al marido aquí.",
    "Can't you hit me?!": "¿¡No puedes darme?!",
    "Chaos, panic and disorder.  My work here is done.": "Caos, pánico y desorden.  Mi trabajo aquí está hecho.",
    "Check enclosed.": "Cheque adjunto.",
    "Check this out!  It's my brain!": "¡Mira esto!  ¡Es mi cerebro!",
    "Chivalry is only reasonably dead": "La caballería solo está razonablemente muerta",
    "Coffin for sale.  Lifetime guarantee.": "Ataúd en venta.  Garantía de por vida.",
    "Come Monday, I'll be all right.": "El lunes que viene, estaré bien.",
    "Come and see the violence inherent in the system": "Ven y ve la violencia inherente al sistema",
    "Come back here!  I'll bite your bloody knees off!": "¡Vuelve aquí!  ¡Te arrancaré las malditas rodillas!",
    "Commodore Business Machines, Inc.  Died for our sins.": "Commodore Business Machines, Inc.  Murió por nuestros pecados.",
    "Complain to one who can help you": "Quéjate a alguien que pueda ayudarte",
    "Confess my sins to god?  Which one?": "¿Confesar mis pecados a dios?  ¿A cuál?",
    "Cooties?  Ain't no cooties on me!": "¿Piojos?  ¡No tengo piojos!",
    "Could somebody get this noose off me?": "¿Podría alguien quitarme esta soga del cuello?",
    "Could you check again?  My name MUST be there.": "¿Podrías comprobarlo otra vez?  Mi nombre DEBE estar ahí.",
    "Could you please take a breath mint?": "¿Podrías tomar un mentolado para el aliento?",
    "Couldn't I be sedated for this?": "¿No podría estar sedado para esto?",
    "Courage is looking at your setbacks with serenity": "Coraje es mirar tus contratiempos con serenidad",
    "Cover me, I'm going in!": "¡Cúbreme, que entro!",
    "Crash course in brain surgery": "Curso intensivo de cirugía cerebral",
    "Cross my fingers for me.": "Cruza los dedos por mí.",
    "Curse god and die": "Maldice a dios y muere",
    "Cut to fit": "Cortar a medida",
    "Dead Again?  Pardon me for not getting it right the first time!": "¿Muerto Otra Vez?  ¡Perdón por no hacerlo bien la primera vez!",
    "Dead and loving every moment!": "¡Muerto y disfrutando cada momento!",
    "Dear wife of mine.  Died of a broken heart, after I took it out of her.": "Querida esposa mía.  Murió de un corazón roto, después de que se lo sacara.",
    "Don't tread on me!": "¡No me pises!",
    "Dragon? What dragon?": "¿Dragón?  ¿Qué dragón?",
    "Drawn and quartered": "Descuartizado",
    "Either I'm dead or my watch has stopped.": "O estoy muerto o mi reloj se ha parado.",
    "Eliza -- Was I really alive, or did I just think I was?": "Eliza -- ¿Estaba realmente viva, o solo pensaba que lo estaba?",
    "Enter not into the path of the wicked": "No entres en el camino de los malvados",
    "Eris?  I don't need Eris": "¿Eris?  No necesito a Eris",
    "Eternal Damnation, Come and stay a long while!": "Condenación Eterna, ¡Ven y quédate un buen rato!",
    "Even The Dead pay taxes (and they aren't Grateful).": "Hasta los Muertos pagan impuestos (y no están Agradecidos).",
    "Even a tomb stone will say good things when you're down!": "¡Hasta una lápida dirá cosas buenas cuando estés abajo!",
    "Ever notice that live is evil backwards?": "¿Has notado que 'live' al revés es 'evil'?",
    "Every day is starting to look like Monday": "Cada día empieza a parecerse al lunes",
    "Every day, in every way, I am getting better and better.": "Cada día, de todas las formas, estoy mejor y mejor.",
    "Every survival kit should include a sense of humor": "Todo kit de supervivencia debería incluir sentido del humor",
    "Evil I did dwell;  lewd did I live": "Viví en el mal;  viví obscenamente",
    "Excellent day to have a rotten day.": "Excelente día para tener un día pésimo.",
    "Excuse me for not standing up.": "Disculpa que no me levante.",
    "Experience isn't everything.  First, you've got to survive.": "La experiencia no lo es todo.  Primero, tienes que sobrevivir.",
    "First shalt thou pull out the Holy Pin": "Primero sacarás el Santo Pasador",
    "For a Breath, I Tarry...": "Por un Respiro, Me Demoro...",
    "For recreational use only.": "Solo para uso recreativo.",
    "For sale: One soul, slightly used.  Asking for 3 wishes.": "Se vende: Un alma, ligeramente usada.  Pido 3 deseos.",
    "For some moments in life, there are no words.": "Para algunos momentos de la vida, no hay palabras.",
    "Forget Disney World, I'm going to Hell!": "Olvida Disney World, ¡me voy al Infierno!",
    "Forget about the dog, Beware of my wife.": "Olvídate del perro, Cuidado con mi esposa.",
    "Funeral - Real fun.": "Funeral - Diversión de verdad.",
    "Game over, man.  Game over.": "Se acabó el juego, tío.  Se acabó.",
    "Gawd, it's depressing in here, isn't it?": "Dios, es deprimente aquí dentro, ¿verdad?",
    "Genuine Exploding Gravestone.  (c)Acme Gravestones Inc.": "Auténtica Lápida Explosiva.  (c)Acme Lápidas Inc.",
    "Get back here!  I'm not finished yet...": "¡Vuelve aquí!  Aún no he terminado...",
    "Go ahead, I dare you to!": "Adelante, ¡a que te atreves!",
    "Go ahead, it's either you or him.": "Adelante, o tú o él.",
    "Got a life.  Didn't know what to do with it.": "Conseguí una vida.  No supe qué hacer con ella.",
    "Grave?  But I was cremated!": "¿Tumba?  ¡Pero si me incineraron!",
    "Greetings from Hell - Wish you were here.": "Saludos desde el Infierno - Ojalá estuvieras aquí.",
    "HELP! It's dark in here....  Oh, my eyes are closed - sorry": "¡AYUDA! Está oscuro aquí....  Ay, tengo los ojos cerrados - lo siento",
    "Ha! I NEVER pay income tax!": "¡Ja! ¡Nunca pago impuestos!",
    "Have you come to raise the dead?": "¿Has venido a resucitar a los muertos?",
    "Having a good time can be deadly.": "Pasarlo bien puede ser mortal.",
    "Having a great time.  Where am I exactly??": "Lo estoy pasando genial.  ¿Dónde estoy exactamente??",
    "He died today....  May we rest in peace!": "Murió hoy....  ¡Que descansemos en paz!",
    "He got the upside, I got the downside.": "Él se quedó lo de arriba, yo me quedé lo de abajo.",
    "He lost his face when he was beheaded.": "Perdió la cara cuando lo decapitaron.",
    "He missed me first.": "Él falló primero.",
    "He's not dead, he just smells that way.": "No está muerto, solo huele así.",
    "Help! I've fallen and I can't get up!": "¡Ayuda! ¡Me he caído y no puedo levantarme!",
    "Help, I can't wake up!": "¡Ayuda, no puedo despertarme!",
    "Here there be dragons": "Aquí hay dragones",
    "Hey, I didn't write this stuff!": "¡Oye, yo no escribí esto!",
    "Hold my calls": "Retén mis llamadas",
    "Home Sweet Hell": "Hogar, dulce Infierno",
    "Humpty Dumpty, a Bad Egg.  He was pushed off the wall.": "Humpty Dumpty, un Huevo Malo.  Lo empujaron del muro.",
    "I KNEW this would happen if I lived long enough.": "SABÍA que esto pasaría si vivía lo suficiente.",
    "I TOLD you I was sick!": "¡TE DIJE que estaba enfermo!",
    "I ain't broke but I am badly bent.": "No estoy roto pero estoy muy doblado.",
    "I ain't old.  I'm chronologically advantaged.": "No soy viejo.  Estoy cronológicamente aventajado.",
    "I am NOT a vampire.  I just like to bite..nibble, really!": "NO soy un vampiro.  Solo me gusta morder... mordisquear, ¡de verdad!",
    "I am here.  Wish you were fine.": "Estoy aquí.  Ojalá estuvieras bien.",
    "I am not dead yet, but watch for further reports.": "No estoy muerto aún, pero espera nuevos informes.",
    "I believe them bones are me.": "Creo que esos huesos son míos.",
    "I broke his brain.": "Le rompí el cerebro.",
    "I can feel it.  My mind.  It's going.  I can feel it.": "Puedo sentirlo.  Mi mente.  Se va.  Puedo sentirlo.",
    "I can't go to Hell.  They're afraid I'm gonna take over!": "No puedo ir al Infierno.  ¡Temen que me apodere del lugar!",
    "I can't go to hell, they don't want me.": "No puedo ir al infierno, no me quieren.",
    "I didn't believe in reincarnation the last time, either.": "Tampoco creía en la reencarnación la última vez.",
    "I didn't mean it when I said 'Bite me'": "No lo decía en serio cuando dije 'Muérdeme'",
    "I died laughing": "Me morí de risa",
    "I disbelieved in reincarnation in my last life, too.": "Tampoco creía en la reencarnación en mi vida anterior.",
    "I hacked myself to death": "Me hackeé hasta morir",
    "I have all the time in the world": "Tengo todo el tiempo del mundo",
    "I have reached Mine's End": "He llegado al Fin de la Mina",
    "I knew I'd find a use for this gravestone!": "¡Sabía que encontraría un uso para esta lápida!",
    "I know my mind.  And it's around here someplace.": "Conozco mi mente.  Y está por aquí en algún sitio.",
    "I lied!  I'll never be alright!": "¡Mentí!  ¡Nunca estaré bien!",
    "I like it better in the dark.": "Prefiero la oscuridad.",
    "I like to be here when I can.": "Me gusta estar aquí cuando puedo.",
    "I may rise but I refuse to shine.": "Puedo levantarme pero me niego a brillar.",
    "I never get any either.": "Yo tampoco recibo ninguno.",
    "I said hit HIM with the fireball, not me!": "¡Dije que le lanzaras la bola de fuego a ÉL, no a mí!",
    "I told you I would never say goodbye.": "Te dije que nunca me despediría.",
    "I used to be amusing.  Now I'm just disgusting.": "Antes era divertido.  Ahora solo doy asco.",
    "I used up all my sick days, so now I'm calling in dead.": "Gasté todos mis días de enfermedad, así que ahora aviso que estoy muerto.",
    "I was killed by <illegible scrawl>": "Fui asesinado por <garabato ilegible>",
    "I was somebody.  Who, is no business of yours.": "Fui alguien.  Quién, no es asunto tuyo.",
    "I will not go quietly.": "No me iré tranquilamente.",
    "I'd give you a piece of my mind... but I can't find it.": "Te daría un pedazo de mi mente... pero no lo encuentro.",
    "I'd rather be breathing": "Prefiero estar respirando",
    "I'll be mellow when I'm dead.  For now, let's PARTY!": "Seré tranquilo cuando esté muerto.  Por ahora, ¡a FIESTAR!",
    "I'm doing this only for tax purposes.": "Hago esto solo por razones fiscales.",
    "I'm not afraid of Death!  What's he gonna do? Kill me?": "¡No le tengo miedo a la Muerte!  ¿Qué va a hacer? ¿Matarme?",
    "I'm not getting enough money, so I'm not going to engrave anything useful here.": "No me pagan lo suficiente, así que no voy a grabar nada útil aquí.",
    "I'm not saying anything.": "No voy a decir nada.",
    "I'm weeth stupeed --->": "Estoy como tonto --->",
    "If you thought you had problems...": "Si creías que tenías problemas...",
    "Ignorance kills daily.": "La ignorancia mata a diario.",
    "Ignore me... I'm just here for my looks!": "Ignórame... ¡Solo estoy aquí por mi buena planta!",
    "Is that all?": "¿Eso es todo?",
    "Is there life before Death?": "¿Hay vida antes de la Muerte?",
    "Is this a joke, or a grave matter?": "¿Esto es una broma, o es un asunto grave?",
    "It happens sometimes.  People just explode.": "A veces pasa.  La gente simplemente explota.",
    "It must be Thursday.  I never could get the hang of Thursdays.": "Debe ser jueves.  Nunca le pillé el truco a los jueves.",
    "It wasn't a fair fight": "No fue una lucha justa",
    "It wasn't so easy.": "No fue tan fácil.",
    "It's Loot, Pillage and THEN Burn...": "Primero Saquear, Pillar y LUEGO Quemar...",
    "Just doing my job here": "Solo haciendo mi trabajo aquí",
    "Killed by diarrhea of mouth and constipation of brain.": "Muerto por diarrea de boca y estreñimiento de cerebro.",
    "Let her RIP": "Dejadla en paz",
    "Let it be; I am dead.": "Déjalo estar; estoy muerto.",
    "Let's play Hide the Corpse": "Juguemos al Escondite del Cadáver",
    "Life is NOT a dream": "La vida NO es un sueño",
    "CONNECT 1964 - NO CARRIER 1994": "CONECTADO 1964 - SIN PORTADORA 1994",
    "Madge Ination -- It wasn't all in my head": "Imagi Nación -- No estaba todo en mi cabeza",
    "Meet me in Heaven": "Encuéntrame en el Cielo",
    "Move on, there's nothing to see here.": "Sigan, no hay nada que ver aquí.",
    "Mr. Flintstone -- Yabba-dabba-done": "Sr. Flintstone -- Yabba-dabba-hecho",
    "My heart is not in this": "Mi corazón no está en esto",
    "No one ever died from it": "Nadie ha muerto nunca por eso",
    "No, you want room 12A, next door.": "No, querrás la habitación 12A, la de al lado.",
    "Nope.  No trap on that chest.  I swear.": "No.  No hay trampa en ese cofre.  Lo juro.",
    "Not again!": "¡Otra vez no!",
    "Not every soil can bear all things": "No toda tierra puede soportar todas las cosas",
    "Now I have a life": "Ahora tengo una vida",
    "Now I lay thee down to sleep... wanna join me?": "Ahora te acuesto a dormir... ¿quieres acompañarme?",
    "OK, here is a question: Where ARE your tanlines?": "Vale, una pregunta: ¿Dónde están tus marcas de bronceado?",
    "Oh! An untimely death.": "¡Oh! Una muerte prematura.",
    "Oh, by the way, how was my funeral?": "Ah, por cierto, ¿cómo fue mi funeral?",
    '"Oh, honey... I missed you!" she said, and fired again.': '"Oh, cariño... ¡te echaba de menos!" dijo ella, y disparó de nuevo.',
    "Ok, so the light does go off.  Now let me out of here.": "Vale, así que la luz se apaga.  Ahora sácame de aquí.",
    "One stone brain": "Un cerebro de piedra",
    "Ooh! Somebody STOP me!": "¡Ooh! ¡Que alguien me PARE!",
    "Oops!": "¡Vaya!",
    "Out for the night.  Leave a message.": "Fuera por la noche.  Deja un mensaje.",
    "Ow!  Do that again!": "¡Ay!  ¡Haz eso otra vez!",
    "Pardon my dust.": "Perdonen mi polvo.",
    "Part of me still works.": "Parte de mí todavía funciona.",
    "Please, not in front of those orcs!": "Por favor, ¡no delante de esos orcos!",
    "Prepare to meet me in Heaven": "Prepárate para encontrarme en el Cielo",
    "Relax.  Nothing ever happens on the first level.": "Relájate.  Nunca pasa nada en el primer nivel.",
    "Rest, rest, perturbed spirit.": "Descansa, descansa, espíritu perturbado.",
    "Rip Torn": "Desgarrado",
    "She always said her feet were killing her but nobody believed her.": "Siempre decía que los pies la estaban matando pero nadie le creía.",
    "She died of a chest cold.": "Murió de un resfriado de pecho.",
    "So let it be written, so let it be done!": "Que así sea escrito, que así sea hecho!",
    "So then I says, How do I know you're the real angel of death?": "Entonces le digo, ¿cómo sé que eres el verdadero ángel de la muerte?",
    "Some patients insist on dying.": "Algunos pacientes insisten en morirse.",
    "Some people have it dead easy, don't they?": "Algunos lo tienen muerto fácil, ¿verdad?",
    "Some things are better left buried.": "Algunas cosas es mejor dejarlas enterradas.",
    "Sure, trust me, I'm a lawyer...": "Claro, confía en mí, soy abogado...",
    "Thank God I wore my corset, because I think my sides have split.": "Gracias a Dios que llevaba corsé, porque creo que me han partido los costados.",
    "That is all": "Eso es todo",
    "The Gods DO have a sense of humor: I'm living proof!": "Los Dioses SÍ tienen sentido del humor: ¡soy la prueba viviente!",
    "The frog's dead.  He Kermitted suicide.": "La rana está muerta.  Se raneicidió.",
    "This dungeon is a pushover": "Esta mazmorra es un paseo",
    "This elevator doesn't go to Heaven": "Este ascensor no va al Cielo",
    "This gravestone is shareware.  To register, please send me 10 zorkmids": "Esta lápida es shareware.  Para registrarla, envíame 10 zorkmids",
    "This gravestone provided by The Yendorian Grave Services Inc.": "Esta lápida proporcionada por Yendorian Servicios Funerarios Inc.",
    "This is not an important part of my life.": "Esta no es una parte importante de mi vida.",
    "This one's on me.": "Esta va por mi cuenta.",
    "This side up": "Este lado hacia arriba",
    "Tim Burr -- Smashed by a tree": "Tronco Gómez -- Aplastado por un árbol",
    "Tone it down a bit, I'm trying to get some rest here.": "Baja el tono un poco, estoy intentando descansar aquí.",
    "Virtually Alive": "Virtualmente Vivo",
    "We Will Meet Again.": "Nos Volveremos a Encontrar.",
    "Weep not, he is at rest": "No llores, él descansa",
    "Welcome to Dante's.  What level please?": "Bienvenido al Infierno de Dante.  ¿Qué nivel?",
    "Well, at least they listened to my sermon...": "Bueno, al menos escucharon mi sermón...",
    "Went to be an angel.": "Se fue para ser un ángel.",
    "What are you doing over there?": "¿Qué haces ahí?",
    "What are you smiling at?": "¿De qué te ríes?",
    "What can you say, Death's got appeal...!": "¿Qué quieres que te diga? La Muerte tiene su atractivo...!",
    "What health care?": "¿Qué sanidad?",
    "What pit?": "¿Qué fosa?",
    "When the gods want to punish you, they answer your prayers.": "Cuando los dioses quieren castigarte, responden tus oraciones.",
    "Where e'er you be let your wind go free.  Keeping it in was the death of me!": "Dondequiera que estés deja libre tu viento.  ¡Retenerlo fue mi muerte!",
    "Where's my refund?": "¿Dónde está mi reembolso?",
    "Will let you know for sure in a day or two...": "Te lo confirmaré en uno o dos días...",
    "Wizards are wimps": "Los magos son gallinas",
    "Worms at work, do not disturb!": "Gusanos trabajando, ¡no molestar!",
    "Would you mind moving a bit?  I'm short of breath down here.": "¿Te importaría moverte un poco?  Me falta el aire aquí abajo.",
    "Would you quit being evil over my shoulder?": "¿Quieres dejar de ser malvado sobre mi hombro?",
    "Ya really had me going baby, but now I'm gone.": "De verdad que me tenías enganchado nena, pero ahora me fui.",
    "Yes Dear, just a few more minutes...": "Sí Cariño, solo unos minutos más...",
    "You said it wasn't poisonous!": "¡Dijiste que no era venenoso!",
    "You set my heart aflame.  You gave me heartburn.": "Prendiste fuego a mi corazón.  Me diste acidez de estómago.",
    "<Expletive Deleted>": "<Improperio Eliminado>",
    "Ilene Toofar -- Fell off a cliff": "Elena Lejos -- Se cayó de un acantilado",
    "Mary had a little lamb/Its fleece was white as snow/When Mary was in trouble/The lamb was first to go": "María tenía un corderito/Su lana era blanca como la nieve/Cuando María estaba en problemas/El cordero fue el primero en irse",
    "Mary had a little lamb/Its fleece was white as snow/When Mary was in trouble/The lamb was first to go": "María tenía un corderito/Su lana era blanca como la nieve/Cuando María estaba en problemas/El cordero fue el primero en irse",
}

# Latin phrases and names - keep as-is
LATIN_SET = {
    "A.S. ->",
    "<- A.S.",
    "Audi Partem Alteram",
    "Auri sacra fames",
    "Auribus teneo lupum",
    "Dulce et decorum est pro patria mori",
    "Et in Arcadia ego",
    "Hodie mihi, cras tibi",
    "Res omnia mea culpa est",
    "Sum quod eris",
    "Tu quoque, Brute?",
    "Ex post fucto",
    "Obesa Cantavit",
}


def main():
    po = polib.pofile(PO_FILE)
    modified = 0
    total = 0

    for entry in po:
        is_ep = any(ref[0] == "dat/epitaph.txt" for ref in entry.occurrences)
        if not is_ep:
            continue

        total += 1

        # Latin phrases - keep as-is (copy msgid to msgstr)
        if entry.msgid in LATIN_SET:
            entry.msgstr = entry.msgid
            modified += 1
            continue

        # Direct translation
        if entry.msgid in TRANSLATIONS:
            entry.msgstr = TRANSLATIONS[entry.msgid]
            modified += 1

    po.save(PO_FILE)

    print(f"Total entradas dat/epitaph.txt: {total}")
    print(f"Traducciones aplicadas: {modified}")
    print(f"Sin traducir: {total - modified}")

    if modified < total:
        print("\n--- Sin traducir ---")
        for entry in po:
            is_ep = any(ref[0] == "dat/epitaph.txt" for ref in entry.occurrences)
            if is_ep and not entry.msgstr:
                print(f"  [{entry.occurrences[0][1]}] {entry.msgid}")


if __name__ == "__main__":
    main()
