#!/usr/bin/env python3
"""
NetHack-es: Segunda pasada de traducción de dat/data.base en po/es.po.

Estrategia:
- Citas literarias [ ... ]: traduce "by" -> "por", "and" -> "y",
  "directed by" -> "dirigida por", etc.
- Claves cortas: usa KEYS.
- Descripciones largas: sustitución palabra-por-palabra con WORD_DICT,
  preservando mayúsculas y nombres propios.
- Diálogos (que empiezan por " o '): se intentan traducir sustituyendo
  palabras sueltas; si no hay coincidencias se dejan sin traducir.
"""

import polib
import re

PO_FILE = "po/es.po"

# ---------------------------------------------------------------------------
# 1) Citas literarias: estructura "[ ..., by Author, ... ]"
# ---------------------------------------------------------------------------
CITATION_REPL = [
    (re.compile(r"\btranslated by\b"), "traducida por"),
    (re.compile(r"\bas translated\b"), "traducida como"),
    (re.compile(r"\bdirected by\b"), "dirigida por"),
    (re.compile(r"\bscreenplay by\b"), "guion de"),
    (re.compile(r"\badapted by\b"), "adaptada por"),
    (re.compile(r"\bnarrated by\b"), "narrada por"),
    (re.compile(r"\bedited by\b"), "editada por"),
    (re.compile(r"\bcompiled by\b"), "compilada por"),
    (re.compile(r"\billustrated by\b"), "ilustrada por"),
    (re.compile(r"\bintroduction by\b"), "introducción de"),
    (re.compile(r"\bforeword by\b"), "prólogo de"),
    (re.compile(r"\bafterword by\b"), "epílogo de"),
    (re.compile(r",\s*from\s+"), ", de "),
    (re.compile(r",\s*in\s+(?=[A-Z])"), ", en "),
    (re.compile(r"\bby\b"), "por"),
    (re.compile(r"\band\b"), "y"),
]


def translate_citation(text: str) -> str:
    """Traduce la estructura de una cita conservando el contenido entre corchetes."""
    m = re.match(r"^(\[\s*)(.*?)(\s*\])$", text)
    if not m:
        return text
    prefix, inner, suffix = m.group(1), m.group(2), m.group(3)
    for pat, repl in CITATION_REPL:
        inner = pat.sub(repl, inner)
    return f"{prefix}{inner}{suffix}"


# ---------------------------------------------------------------------------
# 2) Diccionario de claves cortas (preserva comodines * y ~ al principio).
# ---------------------------------------------------------------------------
KEYS = {
    # Razas y humanoides
    "human": "humano",
    "humanity": "humanidad",
    "elf": "elfo",
    "dwarf": "enano",
    "gnome": "gnomo",
    "hobbit": "hobbit",
    "centaur": "centauro",
    "naga": "naga",
    "nymph": "ninfa",
    "norn": "norna",
    "titan": "titán",
    "cyclops": "cíclope",
    "minotaur": "minotauro",
    "giant": "gigante",
    "troll": "troll",
    "goblin": "goblin",
    "ogre": "ogro",
    "kobold": "kobold",
    "hobgoblin": "hobgoblin",
    "bugbear": "bugbear",
    "gnoll": "gnoll",
    "orc": "orco",
    "ettin": "ettin",
    "balrog": "balrog",
    "marilith": "marilith",
    "pit-fiend": "abismo",
    "imp": "diablillo",
    "dragon": "dragón",
    "wyvern": "wyvern",
    "hydra": "hidra",
    "drake": "draco",
    "dracolich": "draco-liché",
    "dragonnel": "dragonel",
    "demon": "demonio",
    "devil": "diablo",
    "daemon": "daemon",
    "angel": "ángel",
    "archon": "arcángel",
    "arch-devil": "archidiablo",
    "vampire": "vampiro",
    "lich": "liche",
    "demilich": "demiliche",
    "arch-lich": "archiliche",
    "zombie": "zombi",
    "skeleton": "esqueleto",
    "mummy": "momia",
    "ghoul": "ghoul",
    "ghost": "fantasma",
    "spectre": "espectro",
    "wraith": "espectro",
    "wight": "wight",
    "revenant": "revenant",
    "shade": "sombra",
    "vapor": "vapor",
    "dust": "polvo",
    "ice": "hielo",
    "ooze": "limo",
    "blob": "ameba",
    "pudding": "pudín",
    "slime": "moho",
    "jelly": "gelatina",
    "acid": "ácido",
    "black": "negro",
    "shimmering": "relumbrante",
    "burning": "ardiente",
    "sticky": "pegajoso",
    "fiery": "ígneo",
    "floating": "flotante",
    "elemental": "elemental",
    "golem": "gólem",
    "nazgul": "nazgûl",
    "barrow-wight": "wight de túmulo",
    "ameba": "ameba",
    "kobold-lord": "señor kobold",
    # Bestias
    "bat": "murciélago",
    "snake": "serpiente",
    "spider": "araña",
    "rat": "rata",
    "mouse": "ratón",
    "worm": "gusano",
    "leech": "sanguijuela",
    "wolf": "lobo",
    "fox": "zorro",
    "dog": "perro",
    "cat": "gato",
    "horse": "caballo",
    "pony": "poni",
    "kitten": "gatito",
    "puppy": "cachorro",
    "bear": "oso",
    "lion": "león",
    "tiger": "tigre",
    "leopard": "leopardo",
    "panther": "pantera",
    "jaguar": "jaguar",
    "lynx": "lince",
    "cheetah": "guepardo",
    "ape": "mono",
    "monkey": "mono",
    "baboon": "babuino",
    "crocodile": "cocodrilo",
    "alligator": "caimán",
    "lizard": "lagarto",
    "frog": "rana",
    "toad": "sapo",
    "turtle": "tortuga",
    "tuatara": "tuatara",
    "salamander": "salamandra",
    "newt": "tritón",
    "gecko": "gecko",
    "hawk": "halcón",
    "eagle": "águila",
    "owl": "búho",
    "raven": "cuervo",
    "crow": "grajo",
    "duck": "pato",
    "goose": "oca",
    "swan": "cisne",
    "songbird": "pájaro cantor",
    "parrot": "loro",
    "magpie": "urraca",
    "bee": "abeja",
    "wasp": "avispa",
    "hornet": "avispón",
    "ant": "hormiga",
    "beetle": "escarabajo",
    "fly": "mosca",
    "gnat": "mosquito",
    "flea": "pulga",
    "louse": "piojo",
    "tick": "garrapata",
    "moth": "polilla",
    "butterfly": "mariposa",
    "grasshopper": "saltamontes",
    "cricket": "grillo",
    "centipede": "ciempiés",
    "millipede": "milpiés",
    "scorpion": "escorpión",
    "piranha": "piraña",
    "shark": "tiburón",
    "eel": "anguila",
    "octopus": "pulpo",
    "squid": "calamar",
    "crab": "cangrejo",
    "lobster": "bogavante",
    "dolphin": "delfín",
    "whale": "ballena",
    "kraken": "kraken",
    "unicorn": "unicornio",
    "pegasus": "pegaso",
    "hippogriff": "hipogrifo",
    "griffin": "grifo",
    "manticore": "mantícora",
    "sphinx": "esfinge",
    "chimera": "quimera",
    "basilisk": "basilisco",
    "cockatrice": "cockatrice",
    "wyrm": "wyrm",
    "amphisbaena": "anfisbaena",
    # Siglas de monstruos
    "anu": "Anu",
    "ya": "Ya",
    "mog": "Mog",
    "kos": "Kos",
    "ac": "Ac",
    "ack": "ack",
    "jed": "jed",
    "stheno": "stheno",
    "euryale": "euryale",
    "medusa": "Medusa",
    "juju": "juju",
    "ki-rin": "kirin",
    "umber": "umber",
    "umber-hulk": "umber hulk",
    "wumpus": "wumpus",
    "taz": "taz",
    "anshar": "anshar",
    "arioc": "arioc",
    "anhur": "anhur",
    "asmodeus": "Asmodeo",
    "astarte": "Astarte",
    "demogorgon": "Demogorgón",
    "dispater": "Dispater",
    "baalzebub": "Baalzebub",
    "baal": "Baal",
    "yeen": "yeen",
    "binne": "binne",
    "huheno": "huheno",
    "simurgh": "Simurgh",
    "garuda": "Garuda",
    "surya": "Surya",
    "kumar": "Kumar",
    "ash": "ash",
    "ashikaga": "Ashikaga",
    "mori": "Mori",
    "takenouchi": "Takenouchi",
    "bakeneko": "bakeneko",
    "dokuro": "dokuro",
    "anzu": "Anzu",
    "huginn": "Huginn",
    "muninn": "Muninn",
    "bothtrue": "bothtrue",
    "thrym": "Thrym",
    "tarn": "tarn",
    # Roles / profesiones
    "thief": "ladrón",
    "rogue": "pícaro",
    "ranger": "explorador",
    "samurai": "samurái",
    "ninja": "ninja",
    "monk": "monje",
    "priest": "sacerdote",
    "cleric": "clérigo",
    "wizard": "mago",
    "mage": "mago",
    "valkyrie": "valquiria",
    "barbarian": "bárbaro",
    "caveman": "cavernícola",
    "cavewoman": "cavernícola",
    "cave(wo)man": "cavernícola",
    "knight": "caballero",
    "man-at-arms": "hombre de armas",
    "knight-templar": "caballero templario",
    "templar": "templario",
    "warrior": "guerrero",
    "soldier": "soldado",
    "mercenary": "mercenario",
    "guard": "guardia",
    "watchman": "vigilante",
    "captain": "capitán",
    "sergeant": "sargento",
    "lieutenant": "teniente",
    "general": "general",
    "bandit": "bandido",
    "brigand": "brigante",
    "pirate": "pirata",
    "corsair": "corsario",
    "buccaneer": "bucanero",
    "highwayman": "bandolero",
    "assassin": "asesino",
    "thug": "matón",
    "cutpurse": "ratero",
    "robber": "ladrón",
    "burglar": "ladrón",
    "pickpocket": "carterista",
    "mugger": "atracador",
    "acrobat": "acróbata",
    "jester": "bufón",
    "fool": "necio",
    "bard": "bardo",
    "minstrel": "trovador",
    "troubadour": "trovador",
    "dancer": "bailarín",
    "singer": "cantante",
    "musician": "músico",
    "artist": "artista",
    "poet": "poeta",
    "sculptor": "escultor",
    "painter": "pintor",
    "scholar": "erudito",
    "sage": "sabio",
    "philosopher": "filósofo",
    "historian": "historiador",
    "linguist": "lingüista",
    "linguist-lord": "señor lingüista",
    "scientist": "científico",
    "wizard-lord": "señor mago",
    "genie": "genio",
    "djinni": "djinn",
    "efreeti": "efreet",
    "nurse": "enfermera",
    "healer": "sanador",
    "doctor": "doctor",
    "dentist": "dentista",
    "patient": "paciente",
    "tourist": "turista",
    "yeoman": "súbdito",
    "pagen": "paje",
    "squire": "escudero",
    "page": "paje",
    "herald": "heraldo",
    "standard-bearer": "abanderado",
    "champion": "campeón",
    "paladin": "paladín",
    "crusader": "cruzado",
    "inquisitor": "inquisidor",
    "fanatic": "fanático",
    "cultist": "sectario",
    "acolyte": "acólito",
    "abbot": "abad",
    "bishop": "obispo",
    "cardinal": "cardenal",
    "patriarch": "patriarca",
    "archbishop": "arzobispo",
    "pope": "papa",
    "archmage": "archimago",
    "sorcerer": "hechicero",
    "enchantress": "hechicera",
    "necromancer": "nigromante",
    "conjurer": "conjurador",
    "summoner": "invocador",
    "warlock": "brujo",
    "witch": "bruja",
    "warlord": "señor de la guerra",
    "lord": "señor",
    "lady": "dama",
    "queen": "reina",
    "prince": "príncipe",
    "princess": "princesa",
    "king": "rey",
    "emperor": "emperador",
    "empress": "emperatriz",
    "regent": "regente",
    "viceroy": "virrey",
    "duke": "duque",
    "duchess": "duquesa",
    "count": "conde",
    "countess": "condesa",
    "baron": "barón",
    "baroness": "baronesa",
    "marquis": "marqués",
    "marchioness": "marquesa",
    "earl": "conde",
    "viscount": "vizconde",
    "knight-banneret": "caballero pendón",
    "banneret": "pendón",
    "high-king": "gran rey",
    "pretender": "pretendiente",
    "usurper": "usurpador",
    "bachelor": "soltero",
    "spinster": "soltera",
    "widow": "viuda",
    "widower": "viudo",
    "orphan": "huérfano",
    "foundling": "expósito",
    "apprentice": "aprendiz",
    "journeyman": "oficial",
    "master": "maestro",
    "grand-master": "gran maestro",
    "guild-master": "maestro de gremio",
    "master-lord": "maestro",
    "evoker": "evocador",
    "abjurer": "abjurador",
    "diviner": "adivino",
    "transmuter": "transmutador",
    "alchemist": "alquimista",
    "archaeologist": "arqueólogo",
    "archeolog*": "arqueól*",
    "archeologist": "arqueólogo",
    # Materiales
    "iron": "hierro",
    "steel": "acero",
    "silver": "plata",
    "golden": "oro",
    "gold": "oro",
    "copper": "cobre",
    "bronze": "bronce",
    "brass": "latón",
    "platinum": "platino",
    "electrum": "electrum",
    "mithril": "mithril",
    "adamantite": "adamantita",
    "aluminum": "aluminio",
    "tin": "estaño",
    "lead": "plomo",
    "zinc": "zinc",
    "mercury": "mercurio",
    "crystal": "cristal",
    "glass": "vidrio",
    "diamond": "diamante",
    "ruby": "rubí",
    "emerald": "esmeralda",
    "sapphire": "zafiro",
    "jade": "jade",
    "opal": "ópalo",
    "amethyst": "amatista",
    "topaz": "topacio",
    "garnet": "granate",
    "pearl": "perla",
    "ivory": "marfil",
    "bone": "hueso",
    "wooden": "madera",
    "wood": "madera",
    "oak": "roble",
    "maple": "arce",
    "ebony": "ébano",
    "mahogany": "caoba",
    "walnut": "nogal",
    "pine": "pino",
    "birch": "abedul",
    "ash": "fresno",
    "yew": "tejo",
    "elm": "olmo",
    "willow": "sauce",
    "cedar": "cedro",
    "redwood": "secuoya",
    "bamboo": "bambú",
    "rattan": "rattan",
    "leather": "cuero",
    "hide": "piel",
    "pelt": "piel",
    "fur": "pelaje",
    "wool": "lana",
    "silk": "seda",
    "cotton": "algodón",
    "linen": "lino",
    "cloth": "tela",
    "canvas": "lona",
    "velvet": "terciopelo",
    "satin": "satén",
    "taffeta": "tafetán",
    "burlap": "arpillera",
    "felt": "fieltro",
    "gauze": "gasa",
    "muslin": "muselina",
    "crystal-ball": "bola de cristal",
    "crystal-lens": "lente de cristal",
    # Armas
    "sword": "espada",
    "axe": "hacha",
    "bow": "arco",
    "spear": "lanza",
    "dagger": "daga",
    "mace": "maza",
    "club": "porra",
    "whip": "látigo",
    "halberd": "alabarda",
    "pike": "pica",
    "lance": "lanza",
    "javelin": "jabalina",
    "trident": "tridente",
    "glaive": "guja",
    "scythe": "guadaña",
    "staff": "bastón",
    "wand": "varita",
    "quarterstaff": "bastón",
    "crossbow": "ballesta",
    "sling": "honda",
    "arrow": "flecha",
    "bolt": "virote",
    "dart": "dardo",
    "rock": "piedra",
    "stone": "piedra",
    "boulder": "peñasco",
    "cobble": "guijarro",
    "pebble": "guijarro",
    "gem": "gema",
    "gemstone": "gema",
    "ball": "bola",
    "iron-ball": "bola de hierro",
    "chain": "cadena",
    "flail": "mayal",
    "morning-star": "estrella de la mañana",
    "morningstar": "estrella de la mañana",
    "war-hammer": "martillo de guerra",
    "hammer": "martillo",
    "maul": "mazo",
    "pick": "pico",
    "pick-axe": "pico",
    "mattock": "azadón",
    "shovel": "pala",
    "spade": "azada",
    "hoe": "azada",
    "rake": "rastrillo",
    "sickle": "hoz",
    "battle-axe": "hacha de batalla",
    "broad-axe": "hacha ancha",
    "hand-axe": "hacha de mano",
    "throwing-axe": "hacha de lanzar",
    "battleaxe": "hacha de batalla",
    "guisarme": "guisarme",
    "bill-guisarme": "guja",
    "bec-de-corbin": "pico de cuervo",
    "partisan": "partesana",
    "ranseur": "lanza",
    "spetum": "spetum",
    "voulge": "voulge",
    "naginata": "naginata",
    "fauchard": "fauchard",
    "lucern": "lucerna",
    "ancus": "ancus",
    "bardiche": "bardiche",
    "brandistock": "brandistock",
    "dwarvish-mattock": "azadón enano",
    "dwarvish-spear": "lanza enana",
    "dwarvish-short-sword": "espada corta enana",
    "dwarvish-iron-helmet": "casco enano de hierro",
    "elven-arrow": "flecha élfica",
    "elven-bow": "arco élfico",
    "elven-dagger": "daga élfica",
    "elven-spear": "lanza élfica",
    "elven-sword": "espada élfica",
    "elven-mithril-coat": "malla élfica de mithril",
    "elven-cloak": "capa élfica",
    "elven-leather-helm": "casco élfico de cuero",
    "elven-boots": "botas élficas",
    "elven-shield": "escudo élfico",
    "orcbish-arrow": "flecha orca",
    "orcbish-bow": "arco orco",
    "orcbish-short-sword": "espada corta orca",
    "orcbish-mithril-coat": "malla orca de mithril",
    "orcbish-helm": "casco orco",
    "orcbish-shield": "escudo orco",
    "orcbish-spear": "lanza orca",
    "samurai-lord": "samurái",
    "shuriken": "shuriken",
    "boomerang": "bumerán",
    "aklys": "aklys",
    "atlatl": "atlatl",
    "blowgun": "cerbatana",
    "poison-arrow": "flecha envenenada",
    "crossbow-bolt": "virote de ballesta",
    "silver-arrow": "flecha de plata",
    "silver-bullet": "bala de plata",
    "silver-dagger": "daga de plata",
    "silver-sword": "espada de plata",
    "silver-spear": "lanza de plata",
    "silver-wand": "varita de plata",
    "warhammer": "martillo de guerra",
    # Armaduras
    "shield": "escudo",
    "helmet": "casco",
    "boots": "botas",
    "gloves": "guantes",
    "cloak": "capa",
    "armor": "armadura",
    "plate": "placa",
    "mail": "malla",
    "scale-mail": "malla de escamas",
    "banded-mail": "malla de bandas",
    "chain-mail": "cota de malla",
    "plate-mail": "armadura de placas",
    "plate-armor": "armadura de placas",
    "mithril-coat": "malla de mithril",
    "leather-armor": "armadura de cuero",
    "studded-leather-armor": "armadura de cuero tachonado",
    "ring-mail": "malla de anillos",
    "leather-jacket": "chaqueta de cuero",
    "oilskin": "piel aceitada",
    "oilskin-cloak": "capa aceitada",
    "leather-cloak": "capa de cuero",
    "robe": "túnica",
    "cloak-of-protection": "capa de protección",
    "cloak-of-invisibility": "capa de invisibilidad",
    "cloak-of-magic-resistance": "capa de resistencia mágica",
    "cloak-of-displacement": "capa de desplazamiento",
    "cloak-of-elvenkind": "capa élfica",
    "cloak-of-the-dwarvish-lord": "capa del señor enano",
    "helm-of-brightness": "yelmo del brillo",
    "helm-of-telepathy": "yelmo de telepatía",
    "helm-of-opposition": "yelmo de oposición",
    "helm-of-drain-resistance": "yelmo de resistencia al drenaje",
    "helm-of-warning": "yelmo de aviso",
    "gauntlets": "guanteletes",
    "gauntlets-of-dexterity": "guanteletes de destreza",
    "gauntlets-of-power": "guanteletes de poder",
    "gauntlets-of-swimming": "guanteletes de nadar",
    "speed-boots": "botas de velocidad",
    "water-walking-boots": "botas de caminar sobre el agua",
    "jumping-boots": "botas de salto",
    "kicking-boots": "botas de patada",
    "fumble-boots": "botas de torpeza",
    "levitation-boots": "botas de levitación",
    "fire-boots": "botas de fuego",
    "cold-boots": "botas de frío",
    "small-shield": "escudo pequeño",
    "large-shield": "escudo grande",
    "tower-shield": "escudo de torre",
    "kite-shield": "escudo cometa",
    "round-shield": "escudo redondo",
    "buckler": "broquel",
    "crystal-shield": "escudo de cristal",
    "silver-shield": "escudo de plata",
    "mithril-shield": "escudo de mithril",
    "shield-of-reflection": "escudo de reflexión",
    # Objetos: pergaminos / pociones / anillos / varitas / amuletos
    "scroll": "pergamino",
    "potion": "poción",
    "ring": "anillo",
    "amulet": "amuleto",
    "spellbook": "libro de hechizos",
    "book": "libro",
    "tome": "tomo",
    "manual": "manual",
    "tome-of-might": "tomo de poder",
    "tome-of-leadership": "tomo de liderazgo",
    "camera": "cámara",
    "towel": "toalla",
    "blanket": "manta",
    "rope": "cuerda",
    "lantern": "linterna",
    "lamp": "lámpara",
    "oil": "aceite",
    "candle": "vela",
    "candelabrum": "candelabro",
    "torch": "antorcha",
    "flame": "llama",
    "match": "fósforo",
    "matchbox": "caja de fósforos",
    "match-book": "caja de fósforos",
    "bracelet": "brazalete",
    "necklace": "collar",
    "medallion": "medallón",
    "locket": "relicario",
    "talisman": "talismán",
    "charm": "amuleto",
    "trinket": "chuchería",
    "bauble": "chuchería",
    "knick-knack": "baratija",
    "figurine": "figurilla",
    "statue": "estatuilla",
    "idol": "ídolo",
    "icon": "icono",
    "relic": "reliquia",
    "totem": "tótem",
    "bell": "campana",
    "book-of-the-dead": "libro de los muertos",
    "magic-whistle": "silbato mágico",
    "whistle": "silbato",
    "horn": "cuerno",
    "horn-of-plenty": "cuerno de la abundancia",
    "horn-of-fear": "cuerno del miedo",
    "frost-horn": "cuerno de escarcha",
    "fire-horn": "cuerno de fuego",
    "harp": "arpa",
    "flute": "flauta",
    "drum": "tambor",
    "drum-of-earthquake": "tambor de terremoto",
    "drum-of-stunning": "tambor de aturdimiento",
    "magic-flute": "flauta mágica",
    "magic-harp": "arpa mágica",
    "magic-horn": "cuerno mágico",
    "magical-horn": "cuerno mágico",
    "tooled-horn": "cuerno labrado",
    "bugle": "corneta",
    "lyre": "lira",
    "mandolin": "mandolina",
    "banjo": "banjo",
    "lute": "laúd",
    "drum-of-attention": "tambor de atención",
    "war-drum": "tambor de guerra",
    "corpse": "cadáver",
    "egg": "huevo",
    "tins": "latas",
    "tin-opener": "abrelatas",
    "can-opener": "abrelatas",
    "tin-whistle": "silbato de lata",
    "tinning": "conservación",
    "wax": "cera",
    "soap": "jabón",
    "flint": "pedernal",
    "lockpick": "ganzúa",
    "pick-lock": "ganzúa",
    "skeleton-key": "llave maestra",
    "key": "llave",
    "lock": "cerradura",
    "sack": "saco",
    "bag": "bolsa",
    "bag-of-holding": "bolsa de contención",
    "bag-of-tricks": "bolsa de trucos",
    "box": "caja",
    "chest": "cofre",
    "coffer": "cofre",
    "casket": "ataúd",
    "trunk": "baúl",
    "strongbox": "caja fuerte",
    "basket": "cesta",
    "crate": "cajón",
    "case": "estuche",
    "coffin": "ataúd",
    "shackles": "grilletes",
    "iron-balls": "bolas de hierro",
    "manacles": "esposas",
    "grappling-hook": "garfio",
    "hook": "garfio",
    "grapnel": "ancla",
    "anchor": "ancla",
    "bucket": "cubo",
    "pail": "balde",
    "tub": "tina",
    "barrel": "barril",
    "cask": "barril",
    "keg": "barrilete",
    "vat": "tina",
    "tank": "tanque",
    "bowl": "cuenco",
    "cup": "taza",
    "goblet": "copa",
    "chalice": "cáliz",
    "goblet-of-yendor": "copa de Yendor",
    "wine": "vino",
    "ale": "cerveza",
    "water": "agua",
    "milk": "leche",
    "honey": "miel",
    "food": "comida",
    "food-ration": "ración de comida",
    "ration": "ración",
    "cram": "cram",
    "pemmican": "pemmican",
    "lembas": "lembas",
    "tripe": "callos",
    "fortune-cookie": "galleta de la suerte",
    "pancake": "crepe",
    "pie": "pastel",
    "tart": "tarta",
    "cake": "tarta",
    "bread": "pan",
    "loaf": "hogaza",
    "biscuit": "galleta",
    "cookie": "galleta",
    "fruit": "fruta",
    "apple": "manzana",
    "pear": "pera",
    "orange": "naranja",
    "lemon": "limón",
    "banana": "plátano",
    "carrot": "zanahoria",
    "turnip": "nabo",
    "potato": "patata",
    "onion": "cebolla",
    "garlic": "ajo",
    "cabbage": "col",
    "lettuce": "lechuga",
    "tomato": "tomate",
    "cucumber": "pepino",
    "pickle": "pepinillo",
    "olive": "aceituna",
    "mushroom": "seta",
    "truffle": "trufa",
    "cheese": "queso",
    "meat": "carne",
    "beef": "ternera",
    "pork": "cerdo",
    "ham": "jamón",
    "bacon": "beicon",
    "chicken": "pollo",
    "rabbit": "conejo",
    "venison": "venado",
    "fish": "pescado",
    "salmon": "salmón",
    "trout": "trucha",
    "carp": "carpa",
    "tuna": "atún",
    "sardine": "sardina",
    "shellfish": "marisco",
    "snail": "caracol",
    "slug": "babosa",
    # Lugares / estructuras
    "altar": "altar",
    "throne": "trono",
    "tree": "árbol",
    "grave": "tumba",
    "door": "puerta",
    "drawbridge": "puente levadizo",
    "corridor": "pasillo",
    "stairs": "escaleras",
    "fountain": "fuente",
    "sink": "fregadero",
    "pool": "estanque",
    "well": "pozo",
    "moat": "foso",
    "ditch": "zanja",
    "river": "río",
    "stream": "arroyo",
    "creek": "arroyo",
    "brook": "arroyo",
    "lake": "lago",
    "pond": "estanque",
    "sea": "mar",
    "ocean": "océano",
    "bay": "bahía",
    "cove": "cala",
    "harbor": "puerto",
    "port": "puerto",
    "pier": "embarcadero",
    "dock": "muelle",
    "wharf": "muelle",
    "quay": "muelle",
    "bridge": "puente",
    "ford": "vado",
    "tunnel": "túnel",
    "cave": "cueva",
    "cavern": "caverna",
    "grotto": "gruta",
    "mine": "mina",
    "quarry": "cantera",
    "lair": "guarida",
    "den": "cubil",
    "nest": "nido",
    "burrow": "madriguera",
    "hive": "colmena",
    "lodge": "logia",
    "camp": "campamento",
    "fort": "fuerte",
    "fortress": "fortaleza",
    "citadel": "ciudadela",
    "keep": "alcázar",
    "tower": "torre",
    "castle": "castillo",
    "palace": "palacio",
    "manor": "mansión",
    "manor-house": "casa solariega",
    "villa": "villa",
    "cottage": "cabaña",
    "hut": "choza",
    "shack": "choza",
    "cabin": "cabaña",
    "tavern": "taberna",
    "inn": "posada",
    "pub": "taberna",
    "bar": "bar",
    "shop": "tienda",
    "store": "tienda",
    "market": "mercado",
    "bazaar": "bazar",
    "mall": "centro comercial",
    "bank": "banco",
    "temple": "templo",
    "shrine": "santuario",
    "church": "iglesia",
    "cathedral": "catedral",
    "chapel": "capilla",
    "abbey": "abadía",
    "monastery": "monasterio",
    "convent": "convento",
    "priory": "priorato",
    "synagogue": "sinagoga",
    "mosque": "mezquita",
    "pagoda": "pagoda",
    "pyramid": "pirámide",
    "ziggurat": "zigurat",
    "minaret": "minarete",
    "obelisk": "obelisco",
    "dome": "cúpula",
    "arch": "arco",
    "pillar": "pilar",
    "column": "columna",
    "wall": "pared",
    "gate": "puerta",
    "fence": "valla",
    "hedge": "seto",
    "garden": "jardín",
    "orchard": "huerto",
    "vineyard": "viñedo",
    "field": "campo",
    "meadow": "pradera",
    "pasture": "pasto",
    "prairie": "pradera",
    "steppe": "estepa",
    "desert": "desierto",
    "oasis": "oasis",
    "mountain": "montaña",
    "hill": "colina",
    "valley": "valle",
    "ridge": "cresta",
    "cliff": "acantilado",
    "crag": "peñasco",
    "peak": "cumbre",
    "summit": "cima",
    "volcano": "volcán",
    "forest": "bosque",
    "woods": "bosque",
    "grove": "arboleda",
    "jungle": "jungla",
    "swamp": "pantano",
    "marsh": "marisma",
    "bog": "turbera",
    "moor": "páramo",
    "heath": "brezal",
    "fen": "marisma",
    "mire": "fango",
    "beach": "playa",
    "shore": "orilla",
    "coast": "costa",
    "strand": "playa",
    "island": "isla",
    "islet": "islote",
    "archipelago": "archipiélago",
    "peninsula": "península",
    "cape": "cabo",
    "point": "punta",
    "promontory": "promontorio",
    # Varios
    "set": "conjunto",
    "system": "sistema",
    "kit": "equipo",
    "war": "guerra",
    "win": "victoria",
    "loss": "derrota",
    "victory": "victoria",
    "death": "muerte",
    "life": "vida",
    "love": "amor",
    "hate": "odio",
    "fear": "miedo",
    "hope": "esperanza",
    "faith": "fe",
    "luck": "suerte",
    "fate": "destino",
    "doom": "perdición",
    "boss": "jefe",
    "elite": "élite",
    "rare": "raro",
    "common": "común",
    "uncommon": "poco común",
    "unique": "único",
    "epic": "épico",
    "legendary": "legendario",
    "mythic": "mítico",
    "mythical": "mítico",
    "ancient": "antiguo",
    "elder": "anciano",
    "old": "viejo",
    "young": "joven",
    "great": "gran",
    "small": "pequeño",
    "tiny": "diminuto",
    "huge": "enorme",
    "large": "grande",
    "big": "grande",
    "gigantic": "gigantesco",
    "strong": "fuerte",
    "weak": "débil",
    "fast": "rápido",
    "slow": "lento",
    "quick": "veloz",
    "swift": "veloz",
    "lazy": "perezoso",
    "smart": "listo",
    "clever": "ingenioso",
    "wise": "sabio",
    "foolish": "necio",
    "stupid": "estúpido",
    "dumb": "mudo",
    "deaf": "sordo",
    "blind": "ciego",
    "lame": "cojo",
    "sick": "enfermo",
    "healthy": "sano",
    "rich": "rico",
    "poor": "pobre",
    "happy": "feliz",
    "sad": "triste",
    "angry": "enfadado",
    "calm": "calmado",
    "peaceful": "pacífico",
    "violent": "violento",
    "kind": "amable",
    "cruel": "cruel",
    "evil": "malvado",
    "good": "bueno",
    "neutral": "neutral",
    "chaotic": "caótico",
    "lawful": "legal",
    "alignment": "alineamiento",
    "arnor": "Arnor",
    "gondor": "Gondor",
    "rohan": "Rohan",
    "mordor": "Mordor",
    "rivendell": "Rivendel",
    "lothlorien": "Lothlórien",
    "moria": "Moria",
    "isengard": "Isengard",
    "edoras": "Edoras",
    "hobbiton": "Hobbiton",
    "bree": "Bree",
    "shire": "la Comarca",
    "ankh-morpork": "Ankh-Morpork",
    "pseudopolis": "Pseudópolis",
    "ramtops": "Ramtops",
    "lancre": "Lancre",
    "sokoban": "Sokoban",
    "gehennom": "Gehennom",
    "yendor": "Yendor",
    "ath": "ath",
    "au": "au",
    "r": "r",
    "do": "do",
    "dos": "dos",
    "ru": "ru",
    "wer": "wer",
    "aths": "aths",
    "parasol": "parasol",
    "clover": "trébol",
    "poppy": "amapola",
    "acorn": "bellota",
    "pinecone": "piña",
    "sprig": "ramita",
    "withered": "marchita",
    "blooming": "floreciente",
    # Lugares de NetHack
    "the-mines": "las minas",
    "the-quest": "la búsqueda",
    "the-castle": "el castillo",
    "the-astral-plane": "el plano astral",
    "the-oracle": "el oráculo",
    "the-sanctum": "el sanctasanctórum",
    "the-valley-of-the-dead": "el valle de los muertos",
    "medusa's-lair": "la guarida de Medusa",
    # Abreviaturas internas de NetHack
    "an-": "ana-",
    "an.": "ana.",
    "jr": "Jr",
    "lrd": "lrd",
    "sgn": "sgn",
    "shk": "shk",
    "blk": "blk",
    "nm": "nm",
    "hp": "hp",
    "xtra": "xtra",
    "cha": "car",
    "int": "int",
    "wis": "sab",
    "dex": "des",
    "str": "fue",
    "con": "con",
    "dnd": "dnd",
    "xp": "pe",
    "dungeon": "mazmorra",
    "dungeons": "mazmorras",
    # Claves adicionales con comodines *
    "cope": "capa",
    "lava": "lava",
    "polearm": "arma de asta",
    "amnesia": "amnesia",
    "arthur": "Arturo",
    "booze": "alcohol",
    "broadsword": "espada ancha",
    "camaxtli": "Camaxtle",
    "canine": "canino",
    "coin": "moneda",
    "epidaurus": "Epidauro",
    "feline": "felino",
    "frond": "fronda",
    "fungus": "hongo",
    "gargoyle": "gárgola",
    "grease": "grasa",
    "h?nnom": "Gehennom",
    "horseman": "jinete",
    "hulk": "mole",
    "jackal": "chacal",
    "jackals": "chacales",
    "kop": "keystone kop",
    "mimic": "mímico",
    "molds": "moldes",
    "naja": "naja",
    "pall": "palio",
    "paper": "papel",
    "piercer": "perforador",
    "portal": "portal",
    "quest": "búsqueda",
    "saber": "sable",
    "sabre": "sable",
    "shoes": "zapatos",
    "sphere": "esfera",
    "spore": "espora",
    "stalker": "acechador",
    "venom": "veneno",
    "vortex": "vórtice",
    "wolfsbane": "acónito",
    "xoth": "Xoth",
    "yugake": "yugake",
    "zombi": "zombi",
    # Mitología nórdica
    "odin": "Odín",
    "thor": "Thor",
    "loki": "Loki",
    "freya": "Freya",
    "freyr": "Freyr",
    "heimdall": "Heimdall",
    "tyr": "Tyr",
    "njord": "Njörð",
    "skadi": "Skaði",
    "balder": "Baldr",
    "valhalla": "Valhalla",
    "asgard": "Asgard",
    "midgard": "Midgard",
    "jotunheim": "Jotunheim",
    "vanaheim": "Vanaheim",
    "alfheim": "Alfheim",
    "svartalfheim": "Svartalfheim",
    "muspelheim": "Muspelheim",
    "niflheim": "Niflheim",
    "bifrost": "Bifrost",
    "yggdrasil": "Yggdrasil",
    "mimir": "Mimir",
    "kvasir": "Kvasir",
    "fenrir": "Fenrir",
    "sleipnir": "Sleipnir",
    "huginn2": "Huginn",
    "muninn2": "Muninn",
    # Otras claves misceláneas
    "?atriarch": "patriarca",
    "?riar": "fraile",
    "amulet2": "amuleto",
    "athame": "atame",
    "athames": "atames",
}


# ---------------------------------------------------------------------------
# 3) Nombres propios (no se traducen).
# ---------------------------------------------------------------------------
PROPER_NOUNS = {
    # Dioses y figuras mitológicas
    "yendor",
    "elbereth",
    "moloch",
    "asmodeus",
    "dispater",
    "baalzebub",
    "demogorgon",
    "astarte",
    "anhur",
    "arioc",
    "shub-niggurath",
    "cthulhu",
    "nyarlathotep",
    "hastur",
    "yog-sothoth",
    "azathoth",
    "dagon",
    "lilith",
    "ishtar",
    "isis",
    "osiris",
    "anubis",
    "thoth",
    "horus",
    "ra",
    "amun",
    "ptah",
    "set",
    "seth",
    "bast",
    "sekhmet",
    "marduk",
    "nabu",
    "tiamat",
    "ming",
    "yam",
    "maui",
    "tane",
    "tangaroa",
    "benu",
    "ammit",
    "montu",
    "sopdet",
    "sothis",
    "sirius",
    "orion",
    "antares",
    "spica",
    "aldebaran",
    "altair",
    "deneb",
    "vega",
    "rigel",
    "betelgeuse",
    "canopus",
    "procyon",
    "pollux",
    "castor",
    "regulus",
    "algol",
    "polaris",
    "thuban",
    # Arthuriana
    "arthur",
    "lancelot",
    "gawain",
    "galahad",
    "percival",
    "perceval",
    "tristan",
    "isolde",
    "guinevere",
    "morgan",
    "morgaine",
    "merlin",
    "avalon",
    "camelot",
    "pendragon",
    "uther",
    "mordred",
    "medraut",
    "galahad",
    "gwalchmai",
    "bedwyr",
    "kay",
    "keie",
    "pellinore",
    "diana",
    "artemis",
    "apollo",
    "athena",
    "athene",
    "minerva",
    "zeus",
    "jupiter",
    "hera",
    "juno",
    "poseidon",
    "neptune",
    "hades",
    "pluto",
    "demeter",
    "ceres",
    "aphrodite",
    "venus",
    "ares",
    "mars",
    "hephaestus",
    "vulcan",
    "hermes",
    "hestia",
    "vesta",
    "dionysus",
    "bacchus",
    "pan",
    "selene",
    "helios",
    "eos",
    "nike",
    "nemesis",
    "tyche",
    "fortuna",
    "moirai",
    "fates",
    "parcae",
    "erinyes",
    "furies",
    "eumenides",
    "scylla",
    "charybdis",
    "mino",
    "minos",
    "ariadne",
    "theseus",
    "iphigenia",
    "hercules",
    "herakles",
    "alcides",
    "cacus",
    "geryon",
    "geryones",
    "diomedes",
    "hippolyte",
    "eurytion",
    "eurytus",
    "neleus",
    "periclymenus",
    "antaeus",
    "busiris",
    "ixion",
    "tityos",
    "tantalus",
    "sisyphus",
    "phlegethon",
    "lethe",
    "styx",
    "acheron",
    "cocytus",
    "erebus",
    "elysium",
    "asphodel",
    "tartarus",
    "chaos",
    "gaia",
    "ge",
    "phanes",
    "nyx",
    "hemera",
    "aether",
    "pontus",
    "ouranos",
    "uranus",
    "kronos",
    "cronus",
    "cronos",
    "rhea",
    "coeus",
    "coios",
    "crius",
    "krios",
    "hyperion",
    "iapetus",
    "iapetos",
    "theia",
    "thea",
    "mnemosyne",
    "themis",
    "atlas",
    "prometheus",
    "epimetheus",
    "pandora",
    "deucalion",
    "pyrrha",
    "io",
    "io2",
    "io3",
    "io4",
    "europa",
    "europe",
    "asia",
    "africa",
    "americas",
    "callisto",
    "callisto2",
    "callisto3",
    "callisto4",
    "lycaon",
    "lycaon2",
    "lycaon3",
    "lycaon4",
    "arachne",
    "medea",
    "jason",
    "argonauts",
    "argonaut",
    "atalanta",
    "iphicles",
    "alcathous",
    "tydeus",
    "amphiarus",
    "capaneus",
    "hippomedon",
    "parthenopaeus",
    "admetus",
    "alcestis",
    "peleus",
    "thetis",
    "achilles",
    "patroclus",
    "ajax",
    "teucer",
    "diomedes",
    "ulysses",
    "odysseus",
    "penelope",
    "telemachus",
    "circe",
    "calypso",
    "nestor",
    "menelaus",
    "agamemnon",
    "clytemnestra",
    "orestes",
    "electra",
    "iphigenia",
    "iphigenia2",
    "iphigenia3",
    "iphigenia4",
    "iphigenia5",
    "iphigenia6",
    "iphigenia7",
    "iphigenia8",
    "iphigenia9",
    "iphigenia10",
    "iphigenia11",
    "iphigenia12",
    "iphigenia13",
    "iphigenia14",
    "iphigenia15",
    "iphigenia16",
    # Tolkien
    "tolkien",
    "gandalf",
    "saruman",
    "sauron",
    "frodo",
    "sam",
    "samwise",
    "merry",
    "pippin",
    "aragorn",
    "legolas",
    "gimli",
    "boromir",
    "denethor",
    "theoden",
    "eowyn",
    "eomer",
    "treebeard",
    "bombadil",
    "elrond",
    "galadriel",
    "celeborn",
    "arwen",
    "celebrimbor",
    "glorfindel",
    "mithrandir",
    "olorin",
    "valinor",
    "numenor",
    "beleriand",
    "doriath",
    "nargothrond",
    "angband",
    "edoras",
    "hobbiton",
    "edor",
    # Pratchett / Mundodisco
    "rincewind",
    "luggage",
    "conina",
    "twoflower",
    "mort",
    "morty",
    "yertle",
    "erigorm",
    "vetinari",
    "vimes",
    "colon",
    "nobbs",
    "nobby",
    "detritus",
    "angua",
    "carrot",
    "ironfoundersson",
    "dorfl",
    "sally",
    "willikins",
    "rust",
    "havelock",
    "samuel",
    "sybil",
    "ruth",
    "agnes",
    "nanny",
    "ogga",
    "magrat",
    "verence",
    "shawn",
    "ramos",
    "blowitt",
    "vitellius",
    "ridcully",
    "cohen",
    "ghengiz",
    "hugo",
    "barking",
    # Lovecraft y similares
    "lovecraft",
    "dunwich",
    "innsmouth",
    "arkham",
    "r'lyeh",
    "rlyeh",
    "rlyeh2",
    "rlyeh3",
    "rlyeh4",
    "rlyeh5",
    "rlyeh6",
    "rlyeh7",
    "rlyeh8",
    "rlyeh9",
    "rlyeh10",
    "necronomicon",
    "eltdown",
    # Leiber
    "leiber",
    "fafhrd",
    "graymouser",
    "grey-mouser",
    "gray-mouser",
    # Moorcock
    "moorecock",
    "moorcock",
    "elric",
    "stormbringer",
    "yyrkoon",
    "moonglum",
    # Conan / Howard
    "conan",
    "cimmerian",
    "howard",
    "robert",
    "valeria",
    "bêlit",
    "belit",
    "thoth-amon",
    "thothamon",
    "thoth-amon",
    "set",
    "yezud",
    "yezud2",
    # D&D y similares
    "yog",
    "sothoth",
    "sothoth2",
    "sothoth3",
    "sothoth4",
    "sothoth5",
    "sothoth6",
    "sothoth7",
    "sothoth8",
    "sothoth9",
    "sothoth10",
    # Otros nombres propios frecuentes
    "huck",
    "huckleberry",
    "tom",
    "sawyer",
    "twain",
    "shakespeare",
    "dickens",
    "austen",
    "bronte",
    "eliot",
    "hardy",
    "thackeray",
    "melville",
    "poe",
    "irving",
    "hawthorne",
    "james",
    "wharton",
    "faulkner",
    "fitzgerald",
    "hemingway",
    "steinbeck",
    "wolfe",
    "wolfe2",
    "wolfe3",
    "wolfe4",
    "wolfe5",
    "wolfe6",
    "wolfe7",
    "wolfe8",
    "wolfe9",
    "wolfe10",
    # Personajes literarios recurrentes en NetHack
    "hastur",
    "hastur2",
    "hastur3",
    "hastur4",
    "hastur5",
    "dagon",
    "dagon2",
    "dagon3",
    "dagon4",
    "dagon5",
    "trymon",
    "offler",
    "rincewind",
    "twoflower",
    "luggage",
    "vimes",
    "vetinari",
    "ridcully",
    "banastre",
    "tar",
    "orome",
    "orome2",
    "orome3",
    "ulmo",
    "aule",
    "mandos",
    "lorien",
    "tulkas",
    "nienna",
    "yavanna",
    "varda",
    "manwe",
    "manwe2",
    "manwe3",
    "manwe4",
    "manwe5",
    "morgoth",
    "melkor",
    "ungoliant",
    "glaurung",
    "ancalagon",
    "smaug",
    "scatha",
    "carcaroth",
    "carcharoth",
    "turin",
    "túrin",
    "hurin",
    "huor",
    "beren",
    "luthien",
    "thingol",
    "melian",
    "idril",
    "earendil",
    "eärendil",
    "elwing",
    "dior",
    "nimrodel",
    "amroth",
    "celebrian",
    "celebrimbor",
    "curufin",
    "celeborn",
    "galadriel",
    "celeborn2",
    "arwen",
    "arwen2",
    "arwen3",
    "elrond",
    "elrond2",
    "elrond3",
    "isildur",
    "anárion",
    "elendil",
    "valandil",
    "anduin",
    "argon",
    "argon2",
    "argon3",
    "argon4",
    # Nombres propios de lugares / ciudades
    "lankhmar",
    "lankhmar2",
    "lankhmar3",
    "lankhmar4",
    "lankhmar5",
    "lankhmar6",
    "lankhmar7",
    "lankhmar8",
    "lankhmar9",
    "lankhmar10",
    "melnibone",
    "melnibone2",
    "melnibone3",
    "melnibone4",
    "melnibone5",
    "melnibone6",
    "melnibone7",
    "melnibone8",
    "melnibone9",
    "melnibone10",
    "hyboria",
    "cimmeria",
    "cimmeria2",
    "cimmeria3",
    "cimmeria4",
    "cimmeria5",
    "cimmeria6",
    "cimmeria7",
    "cimmeria8",
    "cimmeria9",
    "cimmeria10",
    # Monstruos propios de D&D / NetHack
    "mordor",
    "mordor2",
    "mordor3",
    "mordor4",
    "mordor5",
    "mordor6",
    "mordor7",
    "mordor8",
    "mordor9",
    "mordor10",
    # Lugares y personas del texto NetHack
    "yendor2",
    "yendor3",
    "yendor4",
    "yendor5",
    "rincewind2",
    "rincewind3",
    "rincewind4",
    "rincewind5",
    "rincewind6",
    "rincewind7",
    "rincewind8",
    "rincewind9",
    "rincewind10",
    # Varios
    "hercules",
    "herakles",
    "alcides",
    "alcides2",
    "alcides3",
    "alcides4",
    "alcides5",
    "alcides6",
    "alcides7",
    "alcides8",
    "alcides9",
    "alcides10",
}


# ---------------------------------------------------------------------------
# 4) Diccionario de palabras para sustitución en descripciones largas.
# Se preserva la capitalización original.
# ---------------------------------------------------------------------------
WORD_DICT = {
    # Determinantes, pronombres
    "the": "el",
    "this": "este",
    "that": "ese",
    "these": "estos",
    "those": "esos",
    "such": "tal",
    "any": "algún",
    "some": "algún",
    "all": "todo",
    "every": "cada",
    "each": "cada",
    "both": "ambos",
    "either": "cualquiera",
    "neither": "ninguno",
    "another": "otro",
    "other": "otro",
    "one": "uno",
    "two": "dos",
    "three": "tres",
    "four": "cuatro",
    "five": "cinco",
    "six": "seis",
    "seven": "siete",
    "eight": "ocho",
    "nine": "nueve",
    "ten": "diez",
    "a": "un",
    "an": "un",
    "its": "su",
    "their": "su",
    "her": "su",
    "his": "su",
    "whose": "cuyo",
    "my": "mi",
    "your": "tu",
    "our": "nuestro",
    # to be / to have
    "is": "es",
    "are": "son",
    "was": "era",
    "were": "eran",
    "been": "sido",
    "being": "siendo",
    "be": "ser",
    "am": "soy",
    "has": "tiene",
    "have": "tiene",
    "had": "tenía",
    "having": "teniendo",
    "do": "hacer",
    "does": "hace",
    "did": "hizo",
    "done": "hecho",
    "doing": "haciendo",
    "will": "irá",
    "would": "haría",
    "shall": "deberá",
    "should": "debería",
    "can": "puede",
    "could": "podía",
    "may": "puede",
    "might": "podría",
    "must": "debe",
    "ought": "debería",
    "seem": "parece",
    "seems": "parece",
    "appeared": "apareció",
    "becomes": "se convierte",
    "became": "se convirtió",
    "become": "convertirse",
    # Verbos comunes
    "make": "hacer",
    "makes": "hace",
    "made": "hecho",
    "go": "ir",
    "goes": "va",
    "went": "fue",
    "gone": "ido",
    "going": "yendo",
    "come": "venir",
    "comes": "viene",
    "came": "vino",
    "coming": "viniendo",
    "see": "ver",
    "sees": "ve",
    "saw": "vio",
    "seen": "visto",
    "seeing": "viendo",
    "know": "saber",
    "knows": "sabe",
    "knew": "supo",
    "known": "conocido",
    "knowing": "sabiendo",
    "think": "pensar",
    "thinks": "piensa",
    "thought": "pensó",
    "say": "decir",
    "says": "dice",
    "said": "dijo",
    "saying": "diciendo",
    "tell": "contar",
    "tells": "cuenta",
    "told": "contó",
    "telling": "contando",
    "speak": "hablar",
    "speaks": "habla",
    "spoke": "habló",
    "spoken": "hablado",
    "speaking": "hablando",
    "talk": "hablar",
    "talks": "habla",
    "talked": "habló",
    "talking": "hablando",
    "write": "escribir",
    "writes": "escribe",
    "wrote": "escribió",
    "written": "escrito",
    "writing": "escribiendo",
    "read": "leer",
    "reads": "lee",
    "reading": "leyendo",
    "give": "dar",
    "gives": "da",
    "gave": "dio",
    "given": "dado",
    "giving": "dando",
    "take": "tomar",
    "takes": "toma",
    "took": "tomó",
    "taken": "tomado",
    "taking": "tomando",
    "get": "obtener",
    "gets": "obtiene",
    "got": "obtuvo",
    "gotten": "obtenido",
    "getting": "obteniendo",
    "find": "encontrar",
    "finds": "encuentra",
    "found": "encontró",
    "finding": "encontrando",
    "lose": "perder",
    "loses": "pierde",
    "lost": "perdió",
    "losing": "perdiendo",
    "use": "usar",
    "uses": "usa",
    "used": "usado",
    "using": "usando",
    "put": "poner",
    "puts": "pone",
    "putting": "poniendo",
    "set": "poner",
    "sets": "pone",
    "setting": "poniendo",
    "keep": "mantener",
    "keeps": "mantiene",
    "kept": "mantuvo",
    "keeping": "manteniendo",
    "let": "dejar",
    "lets": "deja",
    "letting": "dejando",
    "begin": "comenzar",
    "begins": "comienza",
    "began": "comenzó",
    "begun": "comenzado",
    "beginning": "comenzando",
    "start": "empezar",
    "starts": "empieza",
    "started": "empezó",
    "starting": "empezando",
    "stop": "parar",
    "stops": "para",
    "stopped": "paró",
    "stopping": "parando",
    "end": "terminar",
    "ends": "termina",
    "ended": "terminó",
    "ending": "terminando",
    "finish": "terminar",
    "finishes": "termina",
    "finished": "terminó",
    "finishing": "terminando",
    "continue": "continuar",
    "continues": "continúa",
    "continued": "continuó",
    "continuing": "continuando",
    "try": "intentar",
    "tries": "intenta",
    "tried": "intentó",
    "trying": "intentando",
    "leave": "dejar",
    "leaves": "deja",
    "left": "dejó",
    "leaving": "dejando",
    "call": "llamar",
    "calls": "llama",
    "called": "llamó",
    "calling": "llamando",
    "ask": "preguntar",
    "asks": "pregunta",
    "asked": "preguntó",
    "asking": "preguntando",
    "want": "querer",
    "wants": "quiere",
    "wanted": "quiso",
    "wanting": "queriendo",
    "need": "necesitar",
    "needs": "necesita",
    "needed": "necesitó",
    "needing": "necesitando",
    "feel": "sentir",
    "feels": "siente",
    "felt": "sintió",
    "feeling": "sintiendo",
    "look": "mirar",
    "looks": "mira",
    "looked": "miró",
    "looking": "mirando",
    "appear": "aparecer",
    "appears": "aparece",
    "appeared": "apareció",
    "appearing": "apareciendo",
    "show": "mostrar",
    "shows": "muestra",
    "showed": "mostró",
    "shown": "mostrado",
    "showing": "mostrando",
    "hear": "oír",
    "hears": "oye",
    "heard": "oyó",
    "hearing": "oyendo",
    "listen": "escuchar",
    "listens": "escucha",
    "listened": "escuchó",
    "listening": "escuchando",
    "watch": "observar",
    "watches": "observa",
    "watched": "observó",
    "watching": "observando",
    "move": "mover",
    "moves": "mueve",
    "moved": "movió",
    "moving": "moviendo",
    "run": "correr",
    "runs": "corre",
    "ran": "corrió",
    "running": "corriendo",
    "walk": "caminar",
    "walks": "camina",
    "walked": "caminó",
    "walking": "caminando",
    "fly": "volar",
    "flies": "vuela",
    "flew": "voló",
    "flying": "volando",
    "fall": "caer",
    "falls": "cae",
    "fell": "cayó",
    "fallen": "caído",
    "falling": "cayendo",
    "die": "morir",
    "dies": "muere",
    "died": "murió",
    "dead": "muerto",
    "dying": "muriendo",
    "kill": "matar",
    "kills": "mata",
    "killed": "mató",
    "killing": "matando",
    "slay": "matar",
    "slays": "mata",
    "slew": "mató",
    "slain": "muerto",
    "slaying": "matando",
    "fight": "luchar",
    "fights": "lucha",
    "fought": "luchó",
    "fighting": "luchando",
    "hit": "golpear",
    "hits": "golpea",
    "hitting": "golpeando",
    "strike": "golpear",
    "strikes": "golpea",
    "struck": "golpeó",
    "striking": "golpeando",
    "attack": "atacar",
    "attacks": "ataca",
    "attacked": "atacó",
    "attacking": "atacando",
    "defend": "defender",
    "defends": "defiende",
    "defended": "defendió",
    "defending": "defendiendo",
    "live": "vivir",
    "lives": "vive",
    "lived": "vivió",
    "living": "viviendo",
    "exist": "existir",
    "exists": "existe",
    "existed": "existió",
    "existing": "existiendo",
    "happen": "suceder",
    "happens": "sucede",
    "happened": "sucedió",
    "happening": "sucediendo",
    "occur": "ocurrir",
    "occurs": "ocurre",
    "occurred": "ocurrió",
    "occurring": "ocurriendo",
    "create": "crear",
    "creates": "crea",
    "created": "creó",
    "creating": "creando",
    "destroy": "destruir",
    "destroys": "destruye",
    "destroyed": "destruyó",
    "destroying": "destruyendo",
    "build": "construir",
    "builds": "construye",
    "built": "construyó",
    "building": "construyendo",
    "form": "formar",
    "forms": "forma",
    "formed": "formó",
    "forming": "formando",
    "turn": "girar",
    "turns": "gira",
    "turned": "giró",
    "turning": "girando",
    "hold": "sujetar",
    "holds": "sujeta",
    "held": "sostuvo",
    "holding": "sosteniendo",
    "carry": "llevar",
    "carries": "lleva",
    "carried": "llevó",
    "carrying": "llevando",
    "bring": "traer",
    "brings": "trae",
    "brought": "trajo",
    "bringing": "trayendo",
    "send": "enviar",
    "sends": "envía",
    "sent": "envió",
    "sending": "enviando",
    "receive": "recibir",
    "receives": "recibe",
    "received": "recibió",
    "receiving": "recibiendo",
    "return": "regresar",
    "returns": "regresa",
    "returned": "regresó",
    "returning": "regresando",
    "remember": "recordar",
    "remembers": "recuerda",
    "remembered": "recordó",
    "remembering": "recordando",
    "forget": "olvidar",
    "forgets": "olvida",
    "forgot": "olvidó",
    "forgotten": "olvidado",
    "forgetting": "olvidando",
    "believe": "creer",
    "believes": "cree",
    "believed": "creyó",
    "believing": "creyendo",
    "hope": "esperar",
    "hopes": "espera",
    "hoped": "esperó",
    "hoping": "esperando",
    "wish": "desear",
    "wishes": "desea",
    "wished": "deseó",
    "wishing": "deseando",
    "love": "amar",
    "loves": "ama",
    "loved": "amó",
    "loving": "amando",
    "hate": "odiar",
    "hates": "odia",
    "hated": "odió",
    "hating": "odiando",
    "fear": "temer",
    "fears": "teme",
    "feared": "temió",
    "fearing": "temiendo",
    "worry": "preocupar",
    "worries": "preocupa",
    "worried": "preocupó",
    "worrying": "preocupando",
    # Preposiciones, conjunciones
    "of": "de",
    "in": "en",
    "to": "a",
    "for": "para",
    "with": "con",
    "by": "por",
    "from": "de",
    "at": "en",
    "into": "en",
    "onto": "sobre",
    "upon": "sobre",
    "on": "sobre",
    "off": "fuera de",
    "out": "fuera",
    "over": "sobre",
    "under": "bajo",
    "below": "bajo",
    "above": "sobre",
    "across": "a través de",
    "through": "a través de",
    "between": "entre",
    "among": "entre",
    "within": "dentro de",
    "without": "sin",
    "before": "antes de",
    "after": "después de",
    "during": "durante",
    "since": "desde",
    "until": "hasta",
    "till": "hasta",
    "around": "alrededor de",
    "near": "cerca de",
    "beside": "junto a",
    "behind": "detrás de",
    "beyond": "más allá de",
    "inside": "dentro de",
    "outside": "fuera de",
    "against": "contra",
    "toward": "hacia",
    "towards": "hacia",
    "along": "a lo largo de",
    "down": "abajo",
    "up": "arriba",
    "and": "y",
    "or": "o",
    "but": "pero",
    "nor": "ni",
    "so": "así que",
    "as": "como",
    "if": "si",
    "though": "aunque",
    "although": "aunque",
    "because": "porque",
    "while": "mientras",
    "when": "cuando",
    "where": "donde",
    "wherever": "dondequiera",
    "whether": "si",
    "than": "que",
    "instead": "en lugar",
    "that": "que",
    "which": "que",
    "who": "que",
    "whom": "a quien",
    "what": "lo que",
    "whatever": "lo que sea",
    "whereas": "mientras que",
    # Adverbios
    "very": "muy",
    "really": "realmente",
    "quite": "bastante",
    "somewhat": "algo",
    "almost": "casi",
    "nearly": "casi",
    "just": "sólo",
    "only": "sólo",
    "also": "también",
    "too": "también",
    "even": "incluso",
    "still": "todavía",
    "already": "ya",
    "always": "siempre",
    "never": "nunca",
    "often": "a menudo",
    "sometimes": "a veces",
    "usually": "normalmente",
    "rarely": "raramente",
    "seldom": "rara vez",
    "perhaps": "quizá",
    "maybe": "tal vez",
    "probably": "probablemente",
    "certainly": "ciertamente",
    "surely": "seguramente",
    "definitely": "definitivamente",
    "actually": "en realidad",
    "indeed": "en verdad",
    "truly": "verdaderamente",
    "obviously": "obviamente",
    "clearly": "claramente",
    "apparently": "aparentemente",
    "supposedly": "supuestamente",
    "now": "ahora",
    "then": "entonces",
    "soon": "pronto",
    "later": "más tarde",
    "yesterday": "ayer",
    "today": "hoy",
    "tomorrow": "mañana",
    "here": "aquí",
    "there": "allí",
    "everywhere": "en todas partes",
    "nowhere": "en ninguna parte",
    "somewhere": "en algún lugar",
    "anywhere": "en cualquier lugar",
    "again": "otra vez",
    "once": "una vez",
    "twice": "dos veces",
    "ever": "alguna vez",
    "forever": "para siempre",
    # Adjetivos
    "good": "bueno",
    "bad": "malo",
    "great": "gran",
    "small": "pequeño",
    "large": "grande",
    "big": "grande",
    "little": "pequeño",
    "long": "largo",
    "short": "corto",
    "tall": "alto",
    "high": "alto",
    "low": "bajo",
    "old": "viejo",
    "young": "joven",
    "new": "nuevo",
    "ancient": "antiguo",
    "modern": "moderno",
    "early": "temprano",
    "late": "tarde",
    "first": "primero",
    "last": "último",
    "next": "siguiente",
    "second": "segundo",
    "third": "tercero",
    "main": "principal",
    "primary": "primario",
    "secondary": "secundario",
    "real": "real",
    "true": "verdadero",
    "false": "falso",
    "actual": "real",
    "certain": "cierto",
    "sure": "seguro",
    "possible": "posible",
    "impossible": "imposible",
    "probable": "probable",
    "obvious": "obvio",
    "strange": "extraño",
    "weird": "raro",
    "odd": "raro",
    "peculiar": "peculiar",
    "unusual": "inusual",
    "common": "común",
    "uncommon": "poco común",
    "rare": "raro",
    "unique": "único",
    "special": "especial",
    "general": "general",
    "specific": "específico",
    "particular": "particular",
    "similar": "similar",
    "different": "diferente",
    "same": "mismo",
    "various": "varios",
    "several": "varios",
    "many": "muchos",
    "much": "mucho",
    "few": "pocos",
    "more": "más",
    "most": "más",
    "less": "menos",
    "least": "menos",
    "full": "lleno",
    "empty": "vacío",
    "complete": "completo",
    "incomplete": "incompleto",
    "total": "total",
    "partial": "parcial",
    "whole": "entero",
    "half": "mitad",
    "entire": "entero",
    "beautiful": "hermoso",
    "ugly": "feo",
    "pretty": "bonito",
    "handsome": "apuesto",
    "lovely": "precioso",
    "nice": "agradable",
    "fine": "fino",
    "excellent": "excelente",
    "perfect": "perfecto",
    "wonderful": "maravilloso",
    "awful": "horrible",
    "terrible": "terrible",
    "horrible": "horrible",
    "dreadful": "espantoso",
    "frightful": "espantoso",
    "amazing": "asombroso",
    "astonishing": "asombroso",
    "surprising": "sorprendente",
    "shocking": "chocante",
    "stunning": "impresionante",
    "dark": "oscuro",
    "light": "claro",
    "bright": "brillante",
    "dim": "tenue",
    "pale": "pálido",
    "deep": "profundo",
    "shallow": "poco profundo",
    "black": "negro",
    "white": "blanco",
    "red": "rojo",
    "blue": "azul",
    "green": "verde",
    "yellow": "amarillo",
    "orange": "naranja",
    "purple": "púrpura",
    "violet": "violeta",
    "brown": "marrón",
    "gray": "gris",
    "grey": "gris",
    "pink": "rosa",
    "golden": "dorado",
    "silver": "plateado",
    "crimson": "carmesí",
    "scarlet": "escarlata",
    "azure": "azul",
    "ivory": "marfil",
    "jade": "jade",
    "amber": "ámbar",
    "hot": "caliente",
    "cold": "frío",
    "warm": "cálido",
    "cool": "fresco",
    "icy": "helado",
    "freezing": "helado",
    "burning": "ardiente",
    "dry": "seco",
    "wet": "mojado",
    "damp": "húmedo",
    "moist": "húmedo",
    "heavy": "pesado",
    "thick": "grueso",
    "thin": "delgado",
    "fat": "gordo",
    "skinny": "flaco",
    "slim": "delgado",
    "strong": "fuerte",
    "weak": "débil",
    "powerful": "poderoso",
    "mighty": "poderoso",
    "fierce": "feroz",
    "brave": "valiente",
    "cowardly": "cobarde",
    "timid": "tímido",
    "bold": "audaz",
    "daring": "audaz",
    "fearless": "intrépido",
    "happy": "feliz",
    "sad": "triste",
    "merry": "alegre",
    "cheerful": "alegre",
    "joyful": "alegre",
    "gloomy": "lúgubre",
    "miserable": "mísero",
    "angry": "enfadado",
    "furious": "furioso",
    "calm": "tranquilo",
    "peaceful": "pacífico",
    "violent": "violento",
    "wild": "salvaje",
    "tame": "domesticado",
    "gentle": "suave",
    "harsh": "duro",
    "kind": "amable",
    "cruel": "cruel",
    "evil": "malvado",
    "wicked": "malvado",
    "rich": "rico",
    "poor": "pobre",
    "wealthy": "rico",
    "noble": "noble",
    "royal": "real",
    "regal": "regio",
    "princely": "principesco",
    "holy": "santo",
    "sacred": "sagrado",
    "divine": "divino",
    "profane": "profano",
    "blessed": "bendecido",
    "cursed": "maldito",
    "magical": "mágico",
    "enchanted": "encantado",
    "arcane": "arcano",
    "mystic": "místico",
    "mystical": "místico",
    "occult": "oculto",
    "supernatural": "sobrenatural",
    "natural": "natural",
    "artificial": "artificial",
    "right": "correcto",
    "wrong": "incorrecto",
    "alive": "vivo",
    "living": "vivo",
    "dead": "muerto",
    "lifeless": "sin vida",
    "human": "humano",
    "mortal": "mortal",
    "immortal": "inmortal",
    "finite": "finito",
    "infinite": "infinito",
    "eternal": "eterno",
    "temporal": "temporal",
    "ephemeral": "efímero",
    "transient": "transitorio",
    "permanent": "permanente",
    "temporary": "temporal",
    "endless": "interminable",
    "boundless": "sin límites",
    "limitless": "sin límites",
    "soft": "blando",
    "hard": "duro",
    "rough": "áspero",
    "smooth": "suave",
    "sharp": "afilado",
    "dull": "romo",
    "pointy": "puntiagudo",
    "blunt": "romo",
    "keen": "afilado",
    "acute": "agudo",
    "clean": "limpio",
    "dirty": "sucio",
    "pure": "puro",
    "impure": "impuro",
    "clear": "claro",
    "cloudy": "nublado",
    "murky": "turbio",
    "turbid": "turbio",
    "transparent": "transparente",
    "opaque": "opaco",
    "lucid": "lúcido",
    "obscure": "oscuro",
    "vague": "vago",
    "open": "abierto",
    "closed": "cerrado",
    "shut": "cerrado",
    "loose": "suelto",
    "tight": "apretado",
    "firm": "firme",
    "solid": "sólido",
    "liquid": "líquido",
    "gaseous": "gaseoso",
    "rigid": "rígido",
    "flexible": "flexible",
    "elastic": "elástico",
    "brittle": "quebradizo",
    "tough": "resistente",
    "fragile": "frágil",
    "delicate": "delicado",
    "sturdy": "robusto",
    "robust": "robusto",
    "fancy": "elegante",
    "plain": "sencillo",
    "simple": "simple",
    "complex": "complejo",
    "complicated": "complicado",
    "easy": "fácil",
    "difficult": "difícil",
    "near2": "cercano",
    "far": "lejano",
    "distant": "distante",
    "famous": "famoso",
    "infamous": "infame",
    "notorious": "notorio",
    "renowned": "renombrado",
    "visible": "visible",
    "invisible": "invisible",
    "edible": "comestible",
    "foul": "fétido",
    "stinking": "apestoso",
    "fetid": "fétido",
    "putrid": "pútrido",
    "rotten": "podrido",
    "primordial": "primordial",
    "vile": "vil",
    "nasty": "asqueroso",
    "filthy": "sucio",
    "grimy": "mugriento",
    "greasy": "grasiento",
    "slimy": "baboso",
    "gooey": "pegajoso",
    "mushy": "blandito",
    "soggy": "empapado",
    "watery": "acuoso",
    "glowing": "brillante",
    "shining": "reluciente",
    "shiny": "brillante",
    "sparkling": "centelleante",
    "twinkling": "centelleante",
    "gleaming": "reluciente",
    "glittering": "reluciente",
    "luminous": "luminoso",
    "radiant": "radiante",
    "dazzling": "deslumbrante",
    "blinding": "cegador",
    "shadowy": "umbrío",
    "flickering": "parpadeante",
    "wavering": "tembloroso",
    "burnt": "quemado",
    "scorched": "chamuscado",
    "seared": "marcado",
    "frozen": "helado",
    "frosty": "helado",
    "snowy": "nevado",
    "rainy": "lluvioso",
    "stormy": "tormentoso",
    "windy": "ventoso",
    "breezy": "ventoso",
    "sunny": "soleado",
    "foggy": "brumoso",
    "misty": "brumoso",
    "hazy": "brumoso",
    "rocky": "rocoso",
    "stony": "pedregoso",
    "sandy": "arenoso",
    "muddy": "fangoso",
    "marshy": "pantanoso",
    "swampy": "pantanoso",
    "wooded": "boscoso",
    "forested": "boscoso",
    "grassy": "herboso",
    "leafy": "frondoso",
    "verdant": "verdante",
    "lush": "exuberante",
    "barren": "yermo",
    "desolate": "desolado",
    "bleak": "desolado",
    "dismal": "sombrío",
    "dreary": "sombrío",
    "cheery": "alegre",
    "jolly": "alegre",
    "depressed": "deprimido",
    "melancholy": "melancólico",
    "lonely": "solitario",
    "lonesome": "solitario",
    "solitary": "solitario",
    "alone": "solo",
    "forsaken": "abandonado",
    "abandoned": "abandonado",
    "deserted": "desierto",
    "hollow": "hueco",
    "vacant": "vacante",
    "void": "vacío",
    "nameless": "sin nombre",
    "unknown": "desconocido",
    "familiar": "familiar",
    "unfamiliar": "desconocido",
    "curious": "curioso",
    "bizarre": "bizarro",
    "grotesque": "grotesco",
    "hideous": "horrible",
    "monstrous": "monstruoso",
    "ghastly": "espantoso",
    "gruesome": "macabro",
    "macabre": "macabro",
    "sinister": "siniestro",
    "ominous": "ominoso",
    "foreboding": "presagioso",
    "portentous": "portentoso",
    "fateful": "fatídico",
    "doomed": "condenado",
    "fated": "fatídico",
    "destined": "destinado",
    "lucky": "afortunado",
    "unlucky": "desafortunado",
    "fortunate": "afortunado",
    "unfortunate": "desafortunado",
    "hallowed": "sagrado",
    "venerated": "venerado",
    "revered": "venerado",
    "beloved": "amado",
    "cherished": "querido",
    "adored": "adorado",
    "detested": "detestado",
    "despised": "despreciado",
    "loathed": "aborrecido",
    "scorned": "despreciado",
    "outcast": "marginado",
    "exiled": "exiliado",
    "banished": "desterrado",
    "proscribed": "proscrito",
    # Sustantivos
    "thing": "cosa",
    "things": "cosas",
    "object": "objeto",
    "objects": "objetos",
    "place": "lugar",
    "places": "lugares",
    "world": "mundo",
    "worlds": "mundos",
    "land": "tierra",
    "lands": "tierras",
    "country": "país",
    "nation": "nación",
    "city": "ciudad",
    "town": "pueblo",
    "village": "aldea",
    "hamlet": "aldea",
    "house": "casa",
    "home": "hogar",
    "room": "habitación",
    "rooms": "habitaciones",
    "chamber": "cámara",
    "hall": "salón",
    "hallway": "pasillo",
    "window": "ventana",
    "floor": "suelo",
    "ceiling": "techo",
    "roof": "tejado",
    "step": "escalón",
    "steps": "escalones",
    "staircase": "escalera",
    "ladder": "escalera",
    "path": "camino",
    "pathway": "sendero",
    "road": "carretera",
    "street": "calle",
    "lane": "callejón",
    "alley": "callejón",
    "way": "camino",
    "ways": "caminos",
    "route": "ruta",
    "passage": "pasaje",
    "passageway": "pasadizo",
    "entrance": "entrada",
    "exit": "salida",
    "doorway": "portal",
    "portal": "portal",
    "year": "año",
    "years": "años",
    "day": "día",
    "days": "días",
    "night": "noche",
    "morning": "mañana",
    "evening": "tarde",
    "afternoon": "tarde",
    "time": "tiempo",
    "times": "veces",
    "hour": "hora",
    "hours": "horas",
    "moment": "momento",
    "instant": "instante",
    "second": "segundo",
    "minute": "minuto",
    "century": "siglo",
    "centuries": "siglos",
    "age": "edad",
    "ages": "eras",
    "era": "era",
    "eras": "eras",
    "period": "período",
    "epoch": "época",
    "man": "hombre",
    "men": "hombres",
    "woman": "mujer",
    "women": "mujeres",
    "boy": "niño",
    "girl": "niña",
    "child": "niño",
    "children": "niños",
    "baby": "bebé",
    "infant": "infante",
    "youth": "joven",
    "youths": "jóvenes",
    "adult": "adulto",
    "adults": "adultos",
    "elder": "anciano",
    "elders": "ancianos",
    "person": "persona",
    "people": "gente",
    "folk": "gente",
    "folks": "gente",
    "humans": "humanos",
    "beast": "bestia",
    "beasts": "bestias",
    "creature": "criatura",
    "creatures": "criaturas",
    "monster": "monstruo",
    "monsters": "monstruos",
    "animal": "animal",
    "animals": "animales",
    "plant": "planta",
    "plants": "plantas",
    "trees": "árboles",
    "flower": "flor",
    "flowers": "flores",
    "grass": "hierba",
    "leaf": "hoja",
    "leaves": "hojas",
    "root": "raíz",
    "roots": "raíces",
    "branch": "rama",
    "branches": "ramas",
    "seed": "semilla",
    "seeds": "semillas",
    "fruits": "frutas",
    "vegetable": "verdura",
    "vegetables": "verduras",
    "grain": "grano",
    "grains": "granos",
    "head": "cabeza",
    "face": "cara",
    "eye": "ojo",
    "eyes": "ojos",
    "ear": "oído",
    "ears": "oídos",
    "nose": "nariz",
    "mouth": "boca",
    "tongue": "lengua",
    "tooth": "diente",
    "teeth": "dientes",
    "lip": "labio",
    "lips": "labios",
    "hair": "cabello",
    "beard": "barba",
    "neck": "cuello",
    "throat": "garganta",
    "shoulder": "hombro",
    "shoulders": "hombros",
    "arm": "brazo",
    "arms": "brazos",
    "hand": "mano",
    "hands": "manos",
    "finger": "dedo",
    "fingers": "dedos",
    "thumb": "pulgar",
    "leg": "pierna",
    "legs": "piernas",
    "foot": "pie",
    "feet": "pies",
    "toe": "dedo del pie",
    "toes": "dedos del pie",
    "back": "espalda",
    "chest": "pecho",
    "heart": "corazón",
    "stomach": "estómago",
    "liver": "hígado",
    "bones": "huesos",
    "skin": "piel",
    "blood": "sangre",
    "flesh": "carne",
    "body": "cuerpo",
    "bodies": "cuerpos",
    "soul": "alma",
    "souls": "almas",
    "spirit": "espíritu",
    "spirits": "espíritus",
    "mind": "mente",
    "brain": "cerebro",
    "voice": "voz",
    "voices": "voces",
    "word": "palabra",
    "words": "palabras",
    "name": "nombre",
    "names": "nombres",
    "title": "título",
    "story": "historia",
    "tale": "cuento",
    "tales": "cuentos",
    "legend": "leyenda",
    "legends": "leyendas",
    "myth": "mito",
    "myths": "mitos",
    "fable": "fábula",
    "history": "historia",
    "mystery": "misterio",
    "secret": "secreto",
    "secrets": "secretos",
    "truth": "verdad",
    "lie": "mentira",
    "lies": "mentiras",
    "battle": "batalla",
    "duel": "duelo",
    "duels": "duelos",
    "defeat": "derrota",
    "conquest": "conquista",
    "defense": "defensa",
    "peace": "paz",
    "strife": "conflicto",
    "conflict": "conflicto",
    "kingdom": "reino",
    "empire": "imperio",
    "realm": "reino",
    "domain": "dominio",
    "territory": "territorio",
    "region": "región",
    "province": "provincia",
    "county": "condado",
    "state": "estado",
    # Criaturas / monstruos
    "giants": "gigantes",
    "dragons": "dragones",
    "demons": "demonios",
    "devils": "diablos",
    "angels": "ángeles",
    "goblins": "goblins",
    "orcs": "orcos",
    "elves": "elfos",
    "dwarfs": "enanos",
    "dwarves": "enanos",
    "gnomes": "gnomos",
    "trolls": "trolls",
    "ogres": "ogros",
    "hobbits": "hobbits",
    "snakes": "serpientes",
    "spiders": "arañas",
    "bats": "murciélagos",
    "rats": "ratas",
    "worms": "gusanos",
    "vampires": "vampiros",
    "zombies": "zombis",
    "skeletons": "esqueletos",
    "mummies": "momias",
    "golems": "gólems",
    "elementals": "elementales",
    "nagas": "nagas",
    "liches": "liches",
    "wraiths": "espectros",
    "spectres": "espectros",
    "shades": "sombras",
    "imps": "diablillos",
    "sprites": "duendes",
    "fairies": "hadas",
    "pixies": "pixies",
    "nymphs": "ninfas",
    "naiads": "náyades",
    "nereids": "nereidas",
    "dryads": "driadas",
    "centaurs": "centauros",
    "minotaurs": "minotauros",
    "harpies": "arpías",
    "sirens": "sirenas",
    "mermaids": "sirenas",
    "unicorns": "unicornios",
    "griffins": "grifos",
    "manticores": "mantícoras",
    "sphinxes": "esfinges",
    "chimeras": "quimeras",
    "basilisks": "basiliscos",
    "hydras": "hidras",
    "krakens": "krakens",
    "wyverns": "wyverns",
    "drakes": "dracos",
    "warlocks": "brujos",
    "witches": "brujas",
    "wizards": "magos",
    "sorcerers": "hechiceros",
    "mages": "magos",
    "necromancers": "nigromantes",
    "shamans": "chamanes",
    "priests": "sacerdotes",
    "clerics": "clérigos",
    "monks": "monjes",
    "paladins": "paladines",
    "knights": "caballeros",
    "warriors": "guerreros",
    "soldiers": "soldados",
    "guards": "guardias",
    "thieves": "ladrones",
    "rogues": "pícaros",
    "assassins": "asesinos",
    "bandits": "bandidos",
    "pirates": "piratas",
    "barbarians": "bárbaros",
    "nomads": "nómadas",
    "gypsies": "gitanos",
    "mice": "ratones",
    "cats": "gatos",
    "dogs": "perros",
    "wolves": "lobos",
    "foxes": "zorros",
    "bears": "osos",
    "lions": "leones",
    "tigers": "tigres",
    "horses": "caballos",
    "camels": "camellos",
    "oxen": "bueyes",
    "bulls": "toros",
    "cows": "vacas",
    "sheep": "ovejas",
    "goats": "cabras",
    "pigs": "cerdos",
    "boars": "jabalíes",
    "stags": "ciervos",
    "deer": "ciervos",
    "hares": "liebres",
    "rabbits": "conejos",
    "squirrels": "ardillas",
    "weasels": "comadrejas",
    "apes": "monos",
    "monkeys": "monos",
    "baboons": "babuinos",
    "gorillas": "gorilas",
    "crocodiles": "cocodrilos",
    "alligators": "caimanes",
    "lizards": "lagartos",
    "salamanders": "salamandras",
    "newts": "tritones",
    "frogs": "ranas",
    "toads": "sapos",
    "turtles": "tortugas",
    "chameleons": "camaleones",
    "cobras": "cobras",
    "vipers": "víboras",
    "pythons": "pitones",
    "boas": "boas",
    "adders": "víboras",
    "mambas": "mambas",
    "rattlesnakes": "serpientes de cascabel",
    "anacondas": "anacondas",
    "scorpions": "escorpiones",
    "centipedes": "ciempiés",
    "millipedes": "milpiés",
    "tarantulas": "tarántulas",
    "beetles": "escarabajos",
    "bugs": "insectos",
    "insects": "insectos",
    "flies": "moscas",
    "moths": "polillas",
    "butterflies": "mariposas",
    "wasps": "avispas",
    "hornets": "avispones",
    "bees": "abejas",
    "ants": "hormigas",
    "termites": "termitas",
    "cockroaches": "cucarachas",
    "fleas": "pulgas",
    "lice": "piojos",
    "ticks": "garrapatas",
    "gnats": "mosquitos",
    "mosquitoes": "mosquitos",
    "grasshoppers": "saltamontes",
    "crickets": "grillos",
    "locusts": "langostas",
    "caterpillars": "orugas",
    "larvae": "larvas",
    "fishes": "peces",
    "sharks": "tiburones",
    "rays": "rayas",
    "eels": "anguilas",
    "octopi": "pulpos",
    "squids": "calamares",
    "crabs": "cangrejos",
    "lobsters": "bogavantes",
    "shrimps": "gambas",
    "oysters": "ostras",
    "mussels": "mejillones",
    "clams": "almejas",
    "snails": "caracoles",
    "slugs": "babosas",
    "whales": "ballenas",
    "dolphins": "delfines",
    "seals": "focas",
    "walruses": "morsas",
    "birds": "pájaros",
    "hawks": "halcones",
    "falcons": "halcones",
    "eagles": "águilas",
    "owls": "búhos",
    "ravens": "cuervos",
    "crows": "grajos",
    "magpies": "urracas",
    "sparrows": "gorriones",
    "doves": "palomas",
    "pigeons": "palomas",
    "ducks": "patos",
    "geese": "ocas",
    "swans": "cisnes",
    "parrots": "loros",
    "peacocks": "pavos reales",
    "vultures": "buitres",
    "ostriches": "avestruces",
    # Objetos
    "swords": "espadas",
    "axes": "hachas",
    "bows": "arcos",
    "spears": "lanzas",
    "daggers": "dagas",
    "maces": "mazas",
    "clubs": "porras",
    "whips": "látigos",
    "shields": "escudos",
    "helmets": "cascos",
    "gloves2": "guantes",
    "cloaks": "capas",
    "armors": "armaduras",
    "plates": "placas",
    "scrolls": "pergaminos",
    "rings": "anillos",
    "wands": "varitas",
    "amulets": "amuletos",
    "potions": "pociones",
    "books": "libros",
    "tomes": "tomos",
    "lanterns": "linternas",
    "lamps": "lámparas",
    "torches": "antorchas",
    "candles": "velas",
    "flames": "llamas",
    "fires": "fuegos",
    "stones": "piedras",
    "rocks": "rocas",
    "boulders": "peñascos",
    "pebbles": "guijarros",
    "gems": "gemas",
    "diamonds": "diamantes",
    "rubies": "rubíes",
    "emeralds": "esmeraldas",
    "sapphires": "zafiros",
    "opals": "ópalos",
    "amethysts": "amatistas",
    "crystals": "cristales",
    "crown": "corona",
    "crowns": "coronas",
    "tiara": "tiara",
    "tiaras": "tiaras",
    "sceptre": "cetro",
    "sceptres": "cetros",
    "orb": "orbe",
    "orbs": "orbes",
    "rod": "vara",
    "rods": "varas",
    "staffs": "bastones",
    "coins": "monedas",
    "money": "dinero",
    "treasure": "tesoro",
    "treasures": "tesoros",
    "wealth": "riqueza",
    "riches": "riquezas",
    "loot": "botín",
    "prize": "premio",
    "reward": "recompensa",
    "bounty": "recompensa",
    "gift": "regalo",
    "gifts": "regalos",
    "present": "regalo",
    "offering": "ofrenda",
    "offerings": "ofrendas",
    "sacrifice": "sacrificio",
    "meal": "comida",
    "feast": "festín",
    "banquet": "banquete",
    "dinner": "cena",
    "supper": "cena",
    "lunch": "almuerzo",
    "breakfast": "desayuno",
    "drink": "bebida",
    "drinks": "bebidas",
    "apples": "manzanas",
    "cakes": "tartas",
    "pies": "pasteles",
    "keys": "llaves",
    "locks": "cerraduras",
    "doors": "puertas",
    "gates": "puertas",
    "boxes": "cajas",
    "chests": "cofres",
    "bags": "bolsas",
    "sacks": "sacos",
    "barrels": "barriles",
    "crates": "cajones",
    "bottles": "botellas",
    "flasks": "frascos",
    "vials": "viales",
    "jars": "tarros",
    "pots": "ollas",
    "cups": "tazas",
    "mugs": "tazas",
    "bowls": "cuencos",
    "plates2": "platos",
    "dishes": "platos",
    "spoons": "cucharas",
    "forks": "tenedores",
    "knives": "cuchillos",
    "napkins": "servilletas",
    "tablecloth": "mantel",
    "wicks": "mechas",
    "ropes": "cuerdas",
    "chains": "cadenas",
    "bells": "campanas",
    "whistles": "silbatos",
    "horns": "cuernos",
    "drums": "tambores",
    "harps": "arpas",
    "flutes": "flautas",
    "pipes": "pipas",
    "reeds": "cañas",
    "organs": "órganos",
    "lyres": "liras",
    "fiddles": "violines",
    "violins": "violines",
    "viols": "violas",
    "lutes": "laúdes",
    "citherns": "cítaras",
    "yarn": "hilo",
    "thread": "hilo",
    "needles": "agujas",
    "pins": "alfileres",
    "buttons": "botones",
    "clasps": "broches",
    "buckles": "hebillas",
    "straps": "correas",
    "belts": "cinturones",
    "sashes": "bandas",
    "ribbons": "cintas",
    "jewels": "joyas",
    "jewelry": "joyería",
    "bracelets": "brazaletes",
    "necklaces": "collares",
    "earrings": "pendientes",
    "brooches": "broches",
    "lockets": "relicarios",
    "medallions": "medallones",
    "trinkets": "chucherías",
    "baubles": "baratijas",
    "figurines": "figurillas",
    "idols": "ídolos",
    "totems": "tótems",
    "talismans": "talismanes",
    "relics": "reliquias",
    "charms": "encantos",
    # Lugares
    "castles": "castillos",
    "towers": "torres",
    "forts": "fuertes",
    "fortresses": "fortalezas",
    "citadels": "ciudadelas",
    "keeps": "alcázares",
    "palaces": "palacios",
    "manors": "mansiones",
    "houses": "casas",
    "homes": "hogares",
    "cottages": "cabañas",
    "huts": "chozas",
    "shacks": "chozas",
    "cabins": "cabañas",
    "caves": "cuevas",
    "caverns": "cavernas",
    "grottos": "grutas",
    "mines": "minas",
    "quarries": "canteras",
    "lairs": "guaridas",
    "dens": "cubiles",
    "nests": "nidos",
    "burrows": "madrigueras",
    "hives": "colmenas",
    "lodges": "logias",
    "camps": "campamentos",
    "bridges": "puentes",
    "tunnels": "túneles",
    "temples": "templos",
    "shrines": "santuarios",
    "churches": "iglesias",
    "cathedrals": "catedrales",
    "chapels": "capillas",
    "abbeys": "abadías",
    "monasteries": "monasterios",
    "convents": "conventos",
    "priories": "prioratos",
    "synagogues": "sinagogas",
    "mosques": "mezquitas",
    "pagodas": "pagodas",
    "pyramids": "pirámides",
    "minarets": "minaretes",
    "obelisks": "obeliscos",
    "domes": "cúpulas",
    "arches": "arcos",
    "pillars": "pilares",
    "columns": "columnas",
    "walls": "paredes",
    "fences": "vallas",
    "hedges": "setos",
    "gardens": "jardines",
    "orchards": "huertos",
    "fields": "campos",
    "meadows": "praderas",
    "prairies": "praderas",
    "mountains": "montañas",
    "hills": "colinas",
    "valleys": "valles",
    "ridges": "crestas",
    "cliffs": "acantilados",
    "crags": "peñascos",
    "peaks": "cumbres",
    "volcanoes": "volcanes",
    "forests": "bosques",
    "groves": "arboledas",
    "swamps": "pantanos",
    "marshes": "marismas",
    "bogs": "turberas",
    "moors": "páramos",
    "heaths": "brezales",
    "beaches": "playas",
    "shores": "orillas",
    "islands": "islas",
    "capes": "cabos",
    # Adjetivos materiales
    "iron2": "de hierro",
    "steel2": "de acero",
    "silver2": "de plata",
    "golden2": "de oro",
    "crystal2": "de cristal",
    "glass2": "de vidrio",
    "diamond2": "de diamante",
    "ruby2": "de rubí",
    "emerald2": "de esmeralda",
    "sapphire2": "de zafiro",
    "jade2": "de jade",
    "opal2": "de ópalo",
    "amethyst2": "de amatista",
    "leather2": "de cuero",
    # Adjetivos de estado
    "cursed2": "maldito",
    "uncursed": "no maldito",
    "blessed2": "bendecido",
    "rustproof": "inoxidable",
    "erodeproof": "resistente",
    "dilithium": "dilitio",
    # Conectores y expresiones
    "otherwise": "de lo contrario",
    "anyway": "de todos modos",
    "somehow": "de algún modo",
    "anyhow": "de todos modos",
    "besides": "además",
    "moreover": "además",
    "furthermore": "además",
    "however": "sin embargo",
    "therefore": "por lo tanto",
    "thus": "así",
    "hence": "por tanto",
    "accordingly": "por tanto",
    "consequently": "por tanto",
    "meanwhile": "mientras tanto",
    "afterward": " después",
    "afterwards": " después",
    "beforehand": " antes",
    "ago": "hace",
    "henceforth": "de aquí en adelante",
    "today2": "hoy",
    "tonight": "esta noche",
    "overnight": "durante la noche",
    "lest": "no sea que",
    "albeit": "aunque",
    "notwithstanding": "no obstante",
    # Verbos irregulares
    "ran2": "corrió",
    "running2": "corriendo",
    "walked2": "caminó",
    "walking2": "caminando",
    "flew2": "voló",
    "flying2": "volando",
    "swam": "nadó",
    "swimming": "nadando",
    "swim": "nadar",
    "climbed": "escaló",
    "climbing": "escalando",
    "climb": "escalar",
    "jumped": "saltó",
    "jumping": "saltando",
    "jump": "saltar",
    "leaped": "saltó",
    "leap": "saltar",
    "leaping": "saltando",
    "fell2": "cayó",
    "fallen2": "caído",
    "falling2": "cayendo",
    "rose": "se levantó",
    "rise": "levantarse",
    "rising": "levantándose",
    "raised": "levantó",
    "raise": "levantar",
    "raising": "levantando",
    "dropped": "soltó",
    "drop": "soltar",
    "dropping": "soltando",
    "threw": "lanzó",
    "throw": "lanzar",
    "thrown": "lanzado",
    "throwing": "lanzando",
    "caught": "atrapó",
    "catch": "atrapar",
    "catching": "atrapando",
    "held2": "sostuvo",
    "hold2": "sostener",
    "holding2": "sosteniendo",
    "kept2": "mantuvo",
    "keep2": "mantener",
    "keeping2": "manteniendo",
    "left2": "dejó",
    "leave2": "dejar",
    "leaving2": "dejando",
    "lost2": "perdió",
    "lose2": "perder",
    "losing2": "perdiendo",
    "found2": "encontró",
    "find2": "encontrar",
    "finding2": "encontrando",
    "sought": "buscó",
    "seek": "buscar",
    "seeking": "buscando",
    "hunted": "cazó",
    "hunt": "cazar",
    "hunting": "cazando",
    "chased": "persiguió",
    "chase": "perseguir",
    "chasing": "persiguiendo",
    "followed": "siguió",
    "follow": "seguir",
    "following": "siguiendo",
    "led": "lideró",
    "lead": "liderar",
    "leading": "liderando",
    "directed": "dirigió",
    "direct": "dirigir",
    "directing": "dirigiendo",
    "ordered": "ordenó",
    "order": "ordenar",
    "ordering": "ordenando",
    "demanded": "exigió",
    "demand": "exigir",
    "demanding": "exigiendo",
    "prayed": "rezó",
    "pray": "rezar",
    "praying": "rezando",
    "encouraged": "animó",
    "encourage": "animar",
    "encouraging": "animando",
    "warned": "advirtió",
    "warn": "advertir",
    "warning": "advirtiendo",
    "advised": "aconsejó",
    "advise": "aconsejar",
    "advising": "aconsejando",
    "informed": "informó",
    "inform": "informar",
    "informing": "informando",
    "told2": "dijo",
    "tell2": "decir",
    "telling2": "diciendo",
    "explained": "explicó",
    "explain": "explicar",
    "explaining": "explicando",
    "described": "describió",
    "describe": "describir",
    "describing": "describiendo",
    "complained": "se quejó",
    "complain": "quejarse",
    "complaining": "quejándose",
    "protested": "protestó",
    "protest": "protestar",
    "protesting": "protestando",
    "agreed": "acordó",
    "agree": "acordar",
    "agreeing": "acordando",
    "accepted": "aceptó",
    "accept": "aceptar",
    "accepting": "aceptando",
    "refused": "rechazó",
    "refuse": "rechazar",
    "refusing": "rechazando",
    "rejected": "rechazó",
    "reject": "rechazar",
    "rejecting": "rechazando",
    "denied": "negó",
    "deny": "negar",
    "denying": "negando",
    "admitted": "admitió",
    "admit": "admitir",
    "admitting": "admitiendo",
    "realized": "se dio cuenta",
    "realize": "darse cuenta",
    "realizing": "dándose cuenta",
    "recognized": "reconoció",
    "recognize": "reconocer",
    "recognizing": "reconociendo",
    "imagined": "imaginó",
    "imagine": "imaginar",
    "imagining": "imaginando",
    "supposed": "supuso",
    "suppose": "suponer",
    "supposing": "suponiendo",
    "assumed": "asumió",
    "assume": "asumir",
    "assuming": "asumiendo",
    "suspected": "sospechó",
    "suspect": "sospechar",
    "suspecting": "sospechando",
    "doubted": "dudó",
    "doubt": "dudar",
    "doubting": "dudando",
    "questioned": "cuestionó",
    "question": "cuestionar",
    "questioning": "cuestionando",
    "wondered": "se preguntó",
    "wonder": "preguntarse",
    "wondering": "preguntándose",
    "delighted": "deleitó",
    "delight": "deleitar",
    "delighting": "deleitando",
    "amused": "divirtió",
    "amuse": "divertir",
    "amusing": "divirtiendo",
    "pleased": "complació",
    "please": "complacer",
    "pleasing": "complaciendo",
    "terrified": "aterrorizó",
    "terrify": "aterrorizar",
    "terrifying": "aterrorizando",
    "frightened": "asustó",
    "frighten": "asustar",
    "frightening": "asustando",
    "scared": "asustó",
    "scare": "asustar",
    "scaring": "asustando",
    "startled": "sobresaltó",
    "startle": "sobresaltar",
    "startling": "sobresaltando",
    "surprised": "sorprendió",
    "surprise": "sorprender",
    "surprising": "sorprendiendo",
    "amazed": "asombró",
    "amaze": "asombrar",
    "amazing": "asombrando",
    "shocked": "conmocionó",
    "shock": "conmocionar",
    "shocking": "conmocionando",
    "stunned": "aturdió",
    "stun": "aturdir",
    "stunning": "aturdiendo",
    "confused": "confundió",
    "confuse": "confundir",
    "confusing": "confundiendo",
    "puzzled": "dejó perplejo",
    "puzzle": "dejar perplejo",
    "puzzling": "dejando perplejo",
    "troubled": "preocupó",
    "trouble": "preocupar",
    "troubling": "preocupando",
    "worried2": "preocupó",
    "worry2": "preocupar",
    "worrying2": "preocupando",
    "angered": "enfadó",
    "anger": "enfadar",
    "angering": "enfadando",
    "irritated": "irritó",
    "irritate": "irritar",
    "irritating": "irritando",
    "annoyed": "molestó",
    "annoy": "molestar",
    "annoying": "molestando",
    "involved": "involucró",
    "involve": "involucrar",
    "involving": "involucrando",
    "included": "incluyó",
    "include": "incluir",
    "including": "incluyendo",
    "contained": "contuvo",
    "contain": "contener",
    "containing": "conteniendo",
    "supported": "sostuvo",
    "support": "sostener",
    "supporting": "sosteniendo",
    "maintained": "mantuvo",
    "maintain": "mantener",
    "maintaining": "manteniendo",
    "continued2": "continuó",
    "continue2": "continuar",
    "continuing2": "continuando",
    "persisted": "persistió",
    "persist": "persistir",
    "persisting": "persistiendo",
    "resisted": "resistió",
    "resist": "resistir",
    "resisting": "resistiendo",
    "submitted": "sometió",
    "submit": "someter",
    "submitting": "sometiendo",
    "yielded": "cedió",
    "yield": "ceder",
    "yielding": "cediendo",
    "surrendered": "se rindió",
    "surrender": "rendirse",
    "surrendering": "rindiéndose",
    "obeyed": "obedeció",
    "obey": "obedecer",
    "obeying": "obedeciendo",
    "violated": "violó",
    "violate": "violar",
    "violating": "violando",
    "broke": "rompió",
    "break": "romper",
    "broken": "roto",
    "breaking": "rompiendo",
    "damaged": "dañó",
    "damage": "dañar",
    "damaging": "dañando",
    "destroyed2": "destruyó",
    "destroy2": "destruir",
    "destroying2": "destruyendo",
    "ruined": "arruinó",
    "ruin": "arruinar",
    "ruining": "arruinando",
    "discovered": "descubrió",
    "discover": "descubrir",
    "discovering": "descubriendo",
    "noticed": "notó",
    "notice": "notar",
    "noticing": "notando",
    "observed": "observó",
    "observe": "observar",
    "observing": "observando",
    "remarked": "comentó",
    "remark": "comentar",
    "remarking": "comentando",
    "replied": "respondió",
    "reply": "responder",
    "replying": "respondiendo",
    "answered": "respondió",
    "answer": "responder",
    "answering": "respondiendo",
    "responded": "respondió",
    "respond": "responder",
    "responding": "respondiendo",
    "declared": "declaró",
    "declare": "declarar",
    "declaring": "declarando",
    "stated": "afirmó",
    "state": "afirmar",
    "stating": "afirmando",
    "announced": "anunció",
    "announce": "anunciar",
    "announcing": "anunciando",
    "exclaimed": "exclamó",
    "exclaim": "exclamar",
    "exclaiming": "exclamando",
    "cried": "gritó",
    "cry": "gritar",
    "crying": "gritando",
    "shouted": "gritó",
    "shout": "gritar",
    "shouting": "gritando",
    "yelled": "gritó",
    "yell": "gritar",
    "yelling": "gritando",
    "screamed": "chilló",
    "scream": "chillar",
    "screaming": "chillando",
    "whispered": "susurró",
    "whisper": "susurrar",
    "whispering": "susurrando",
    "muttered": "murmuró",
    "mutter": "murmurar",
    "muttering": "murmurando",
    "moaned": "gimió",
    "moan": "gemir",
    "moaning": "gimiendo",
    "groaned": "gimió",
    "groan": "gemir",
    "groaning": "gimiendo",
    "sighed": "suspiró",
    "sigh": "suspirar",
    "sighing": "suspirando",
    "gasped": "jadeó",
    "gasp": "jadear",
    "gasping": "jadeando",
    "panted": "jadeó",
    "pant": "jadear",
    "panting": "jadeando",
    "breathed": "respiró",
    "breathe": "respirar",
    "breathing": "respirando",
    "laughed": "rió",
    "laugh": "reír",
    "laughing": "riendo",
    "smiled": "sonrió",
    "smile": "sonreír",
    "smiling": "sonriendo",
    "grinned": "sonrió",
    "grin": "sonreír",
    "grinning": "sonriendo",
    "frowned": "frunció",
    "frown": "fruncir",
    "frowning": "frunciendo",
    "glared": "fulminó",
    "glare": "fulminar",
    "glaring": "fulminando",
    "stared": "miró",
    "stare": "mirar",
    "staring": "mirando",
    "gazed": "miró",
    "gaze": "mirar",
    "gazing": "mirando",
    "glanced": "miró",
    "glance": "mirar",
    "glancing": "mirando",
    "peered": "miró",
    "peer": "mirar",
    "peering": "mirando",
    "watched2": "observó",
    "watch2": "observar",
    "watching2": "observando",
    "considered": "consideró",
    "consider": "considerar",
    "considering": "considerando",
    "regarded": "consideró",
    "regard": "considerar",
    "regarding": "considerando",
    "thought2": "pensó",
    "think2": "pensar",
    "thinking2": "pensando",
    "mused": "reflexionó",
    "muse": "reflexionar",
    "musing": "reflexionando",
    "reflected": "reflexionó",
    "reflect": "reflexionar",
    "reflecting": "reflexionando",
    "concluded": "concluyó",
    "conclude": "concluir",
    "concluding": "concluyendo",
    "decided": "decidió",
    "decide": "decidir",
    "deciding": "decidiendo",
    "determined": "determinó",
    "determine": "determinar",
    "determining": "determinando",
    "resolved": "resolvió",
    "resolve": "resolver",
    "resolving": "resolviendo",
    "intended": "intentó",
    "intend": "intentar",
    "intending": "intentando",
    "planned": "planeó",
    "plan": "planear",
    "planning": "planeando",
    "meant": "significó",
    "mean": "significar",
    "meaning": "significando",
    "indicated": "indicó",
    "indicate": "indicar",
    "indicating": "indicando",
    "suggested": "sugirió",
    "suggest": "sugerir",
    "suggesting": "sugiriendo",
    "implied": "implicó",
    "imply": "implicar",
    "implying": "implicando",
    "hinted": "insinuó",
    "hint": "insinuar",
    "hinting": "insinuando",
    "mentioned": "mencionó",
    "mention": "mencionar",
    "mentioning": "mencionando",
    "added": "añadió",
    "add": "añadir",
    "adding": "añadiendo",
    "proceeded": "procedió",
    "proceed": "proceder",
    "proceeding": "procediendo",
    "approached": "se acercó",
    "approach": "acercarse",
    "approaching": "acercándose",
    "arrived": "llegó",
    "arrive": "llegar",
    "arriving": "llegando",
    "departed": "partió",
    "depart": "partir",
    "departing": "partiendo",
    "returned2": "regresó",
    "return2": "regresar",
    "returning2": "regresando",
    "entered": "entró",
    "enter": "entrar",
    "entering": "entrando",
    "exited": "salió",
    "exit": "salir",
    "exiting": "saliendo",
    "passed": "pasó",
    "pass": "pasar",
    "passing": "pasando",
    "crossed": "cruzó",
    "cross": "cruzar",
    "crossing": "cruzando",
    "traveled": "viajó",
    "travel": "viajar",
    "traveling": "viajando",
    "travelled": "viajó",
    "travelling": "viajando",
    "journeyed": "viajó",
    "journey": "viajar",
    "journeying": "viajando",
    "voyaged": "viajó",
    "voyage": "viajar",
    "voyaging": "viajando",
    "wandered": "vagó",
    "wander": "vagar",
    "wandering": "vagando",
    "roamed": "vagó",
    "roam": "vagar",
    "roaming": "vagando",
    "drifted": "vagó",
    "drift": "vagar",
    "drifting": "vagando",
    "strolled": "paseó",
    "stroll": "pasear",
    "strolling": "paseando",
    "prowled": "merodeó",
    "prowl": "merodear",
    "prowling": "merodeando",
    "stalked": "acosó",
    "stalk": "acosar",
    "stalking": "acosando",
    "crept": "se arrastró",
    "creep": "arrastrarse",
    "creeping": "arrastrándose",
    "crawled": "se arrastró",
    "crawl": "arrastrarse",
    "crawling": "arrastrándose",
    "sneaked": "se escabulló",
    "sneak": "escabullirse",
    "sneaking": "escabulléndose",
    "slipped": "se deslizó",
    "slip": "deslizarse",
    "slipping": "deslizándose",
    "glided": "se deslizó",
    "glide": "deslizarse",
    "gliding": "deslizándose",
    "danced": "bailó",
    "dance": "bailar",
    "dancing": "bailando",
    "sang": "cantó",
    "sing": "cantar",
    "singing": "cantando",
    "played": "tocó",
    "play": "tocar",
    "playing": "tocando",
    "performed": "interpretó",
    "perform": "interpretar",
    "performing": "interpretando",
    "recited": "recitó",
    "recite": "recitar",
    "reciting": "recitando",
    "quoted": "citó",
    "quote": "citar",
    "quoting": "citando",
    "chanted": "cantó",
    "chant": "cantar",
    "chanting": "cantando",
    "intoned": "entonó",
    "intone": "entonar",
    "intoning": "entonando",
    "uttered": "pronunció",
    "utter": "pronunciar",
    "uttering": "pronunciando",
    "pronounced": "pronunció",
    "pronounce": "pronunciar",
    "pronouncing": "pronunciando",
    "voiced": "expresó",
    "voice": "expresar",
    "voicing": "expresando",
    "expressed": "expresó",
    "express": "expresar",
    "expressing": "expresando",
    "articulated": "articuló",
    "articulate": "articular",
    "articulating": "articulando",
    "managed": "logró",
    "manage": "lograr",
    "managing": "logrando",
    "succeeded": "logró",
    "succeed": "lograr",
    "succeeding": "logrando",
    "achieved": "logró",
    "achieve": "lograr",
    "achieving": "logrando",
    "accomplished": "logró",
    "accomplish": "lograr",
    "accomplishing": "logrando",
    "attained": "logró",
    "attain": "lograr",
    "attaining": "logrando",
    "obtained": "obtuvo",
    "obtain": "obtener",
    "obtaining": "obteniendo",
    "acquired": "adquirió",
    "acquire": "adquirir",
    "acquiring": "adquiriendo",
    "gained": "ganó",
    "gain": "ganar",
    "gaining": "ganando",
    "earned": "ganó",
    "earn": "ganar",
    "earning": "ganando",
    "won": "ganó",
    "winning": "ganando",
    "spent": "gastó",
    "spend": "gastar",
    "spending": "gastando",
    "wasted": "desperdició",
    "waste": "desperdiciar",
    "wasting": "desperdiciando",
    "lavished": "prodigó",
    "lavish": "prodigar",
    "lavishing": "prodigando",
    "bestowed": "concedió",
    "bestow": "conceder",
    "bestowing": "concediendo",
    "granted": "concedió",
    "grant": "conceder",
    "granting": "concediendo",
    "awarded": "concedió",
    "award": "conceder",
    "awarding": "concediendo",
    "presented": "presentó",
    "present": "presentar",
    "presenting": "presentando",
    "offered": "ofreció",
    "offer": "ofrecer",
    "offering": "ofreciendo",
    "provided": "proveyó",
    "provide": "proveer",
    "providing": "proveyendo",
    "supplied": "suministró",
    "supply": "suministrar",
    "supplying": "suministrando",
    "delivered": "entregó",
    "deliver": "entregar",
    "delivering": "entregando",
    "dispatched": "envió",
    "dispatch": "enviar",
    "dispatching": "enviando",
    "invented": "inventó",
    "invent": "inventar",
    "inventing": "inventando",
    "designed": "diseñó",
    "design": "diseñar",
    "designing": "diseñando",
}


# ---------------------------------------------------------------------------
# 5) Tokenización y sustitución preservando mayúsculas.
# ---------------------------------------------------------------------------
# Divide el texto en palabras y "no-palabras" (espacios, puntuación).
_TOKEN_RE = re.compile(r"([A-Za-z][A-Za-z'-]*|\s+|[^A-Za-z\s])")


def _preserve_case(original: str, translation: str) -> str:
    """Adapta la capitalización de la traducción a la del original."""
    if not translation:
        return translation
    if original.isupper() and len(original) > 1:
        return translation.upper()
    if original[0].isupper():
        return translation[0].upper() + translation[1:]
    return translation


def _lookup(word: str) -> str | None:
    """Busca la traducción de una palabra en PROPER_NOUNS, KEYS y WORD_DICT."""
    lower = word.lower()
    if lower in PROPER_NOUNS:
        return None
    if lower in KEYS:
        return KEYS[lower]
    if lower in WORD_DICT:
        return WORD_DICT[lower]
    return None


def translate_words(text: str) -> str:
    """Sustituye cada palabra suelta por su traducción preservando capitalización."""
    out = []
    for token in _TOKEN_RE.findall(text):
        if not token or not token[0].isalpha():
            out.append(token)
            continue
        tr = _lookup(token)
        if tr is not None:
            out.append(_preserve_case(token, tr))
        else:
            out.append(token)
    return "".join(out)


# ---------------------------------------------------------------------------
# 6) Bucle principal.
# ---------------------------------------------------------------------------
def main() -> None:
    po = polib.pofile(PO_FILE)
    modified = 0
    total = 0
    by_type = {
        "keys": 0,
        "citations": 0,
        "descriptions": 0,
        "dialogue": 0,
        "parenthetical": 0,
        "other": 0,
    }

    for entry in po:
        is_db = any(ref[0] == "dat/data.base" for ref in entry.occurrences)
        if not is_db or entry.msgstr:
            continue

        total += 1
        msgid = entry.msgid
        translated = None

        # --- 1) Citas literarias (pueden ser multi-línea) ---
        if msgid.startswith("["):
            translated = translate_citation(msgid)
            by_type["citations"] += 1

        # --- 2) Claves cortas (con o sin espacios, <30 chars) ---
        if translated is None and len(msgid) < 30:
            prefix = ""
            core = msgid.strip()
            # Quitar prefijos *, ~
            while core[:1] in ("*", "~"):
                prefix += core[:1]
                core = core[1:].lstrip()
            # Quitar sufijos *, ~
            suffix = ""
            while core[-1:] in ("*", "~"):
                suffix = core[-1:] + suffix
                core = core[:-1].rstrip()
            key = core.lower()
            if key in KEYS:
                translated = f"{prefix}{KEYS[key]}{suffix}"
                by_type["keys"] += 1
            elif msgid.strip().lower() in KEYS:
                translated = KEYS[msgid.strip().lower()]
                by_type["keys"] += 1

        # --- 3) Diálogos (entrecomillados): se intentan traducir
        #       sustituyendo palabras sueltas; si no, se dejan. ---
        if translated is None and (msgid.startswith('"') or msgid.startswith("'")):
            candidate = translate_words(msgid)
            if candidate != msgid:
                translated = candidate
                by_type["dialogue"] += 1

        # --- 4) Paréntesis sueltos: igual que diálogo ---
        if translated is None and msgid.startswith("("):
            candidate = translate_words(msgid)
            if candidate != msgid:
                translated = candidate
                by_type["parenthetical"] += 1

        # --- 5) Descripciones largas: sustitución palabra-por-palabra ---
        if translated is None:
            candidate = translate_words(msgid)
            if candidate != msgid:
                translated = candidate
                by_type["descriptions"] += 1

        if translated:
            entry.msgstr = translated
            modified += 1

    po.save(PO_FILE)

    print(f"Total entradas dat/data.base sin traducir: {total}")
    print(f"Traducidas en esta pasada: {modified}")
    print(
        f"  claves={by_type['keys']}, citas={by_type['citations']}, "
        f"descripciones={by_type['descriptions']}, "
        f"diálogos={by_type['dialogue']}, paréntesis={by_type['parenthetical']}"
    )
    print(f"Sin traducir: {total - modified}")


if __name__ == "__main__":
    main()
