#!/usr/bin/env python3
"""
Listas de palabras compartidas entre herramientas de testing y análisis
de NetHack-es.

Centraliza:
  - GAME_TERMS: términos del juego que NO deben traducirse (nombres propios,
    clases, razas, dioses, objetos técnicos, nombres de mazmorra, etc.)
  - SPANISH_WORDS: palabras españolas que coinciden con inglés (falsos
    positivos: "a", "de", "no", "una", etc.)
  - ENGLISH_WORDS: palabras inglesas que indican falta de traducción
"""

# ──── Términos del juego (nombres propios, no traducir) ────

# Roles jugables
ROLE_NAMES = {
    "archeologist",
    "barbarian",
    "caveman",
    "cavewoman",
    "healer",
    "knight",
    "monk",
    "priest",
    "priestess",
    "ranger",
    "rogue",
    "samurai",
    "tourist",
    "valkyrie",
    "wizard",
    "evoker",
    "warrior",
    "fighter",
    "thief",
    "mage",
    "cleric",
    "apprentice",
    "journeyman",
    "expert",
    "master",
    "grandmaster",
    "stripling",
    "whelp",
    "page",
    "yeoman",
    "protector",
    "guardian",
    "defender",
    "footpad",
    "digger",
}

# Razas
RACE_NAMES = {
    "human",
    "elf",
    "dwarf",
    "gnome",
    "orc",
    "gnomish",
    "dwarven",
    "elven",
    "orcish",
    "humanoid",
    "centaur",
    "naga",
    "dragon",
    "giant",
    "titan",
}

# Atributos (técnicos, NO traducir en algunos contextos)
ATTR_NAMES = {
    "strength",
    "dexterity",
    "constitution",
    "intelligence",
    "wisdom",
    "charisma",
}

# Abreviaturas de estado (técnicas)
STAT_ABBREV = {
    "st",
    "dx",
    "co",
    "in",
    "wi",
    "ch",
    "hp",
    "pw",
    "ac",
    "xp",
    "dlvl",
}

# Dioses y nombres de mazmorra
PROPER_NAMES = {
    "moloch",
    "marduk",
    "yendor",
    "amon-ra",
    "amon",
    "set",
    "ishtar",
    "hermes",
    "amaterasu",
    "omikami",
    "the lady",
    "sung",
    "anhur",
    "tyr",
    "quetzalcoatl",
    "crom",
    "mitra",
    "loki",
    "anu",
    "gehennom",
    "under world",
    "dungeons of doom",
    "minetown",
    "mine town",
    "oracle",
    "oracles",
    "sokoban",
    "ludios",
    "medusa",
    "castle",
    "valley",
    "astral",
    "quest",
    "elemental planes",
    "plane of",
}

# Objetos técnicos (tipos de item que se usan como identificadores)
ITEM_TYPES = {
    "amulet",
    "artifact",
    "potion",
    "scroll",
    "wand",
    "ring",
    "spellbook",
    "spell",
    "book",
    "weapon",
    "armor",
    "helm",
    "gloves",
    "boots",
    "shield",
    "sword",
    "dagger",
    "axe",
    "bow",
    "arrow",
    "club",
    "mace",
    "spear",
    "staff",
    "food",
    "ration",
    "chest",
    "box",
    "bag",
    "sack",
    "candelabrum",
    "invocation",
    "bell",
}

# Monstruos comunes (nombres en inglés del juego)
MONSTER_NAMES = {
    "gnome",
    "dwarf",
    "elf",
    "orc",
    "hobbit",
    "kobold",
    "leprechaun",
    "nymph",
    "vampire",
    "zombie",
    "ghost",
    "wraith",
    "demon",
    "devil",
    "imp",
    "succubus",
    "incubus",
    "goblin",
    "ogre",
    "troll",
    "giant",
}

# Nombres de comandos (técnicos, no traducir en la lista de comandos)
COMMAND_NAMES = {
    "pickup",
    "loot",
    "chat",
    "tip",
    "swap",
    "wipe",
    "dip",
    "enhance",
    "adjust",
    "annotate",
    "monster",
    "notes",
    "reveal",
    "turn",
    "version",
    "time",
    "look",
    "sit",
    "pray",
    "offer",
    "seppuku",
    "genocide",
    "teleport",
    "levelport",
    "tribute",
    "experience",
    "tutorial",
    "guide",
}

# Nombres de terrenos (en inglés, usados internamente)
TERRAIN_NAMES = {
    "floor",
    "wall",
    "corridor",
    "door",
    "stairs",
    "trap",
    "altar",
    "fountain",
    "sink",
    "pool",
    "water",
    "lava",
    "ice",
    "tree",
}

# Tutorial y licencia (intencionalmente en inglés)
TUTORIAL_TERMS = {
    "tutorial",
    "skip",
    "options",
    "keyboard",
    "controls",
    "commands",
}

# Licencia MIT (intencionalmente en inglés)
LICENSE_TERMS = {
    "permission",
    "hereby",
    "granted",
    "free",
    "charge",
    "any",
    "person",
    "obtaining",
    "a copy",
    "this software",
    "associated",
    "documentation",
    "files",
    "deal",
    "without",
    "restriction",
    "including",
    "without limitation",
    "limitation",
    "rights",
    "use",
    "modify",
    "merge",
    "publish",
    "distribute",
    "sublicense",
    "sell",
    "copies",
    "subject",
    "following",
    "conditions",
    "above",
    "copyright",
    "notice",
    "shall",
    "included",
    "all",
    "substantial",
    "portions",
    "the software",
    "the copyright",
}

# Unión de todos los términos del juego
GAME_TERMS = (
    ROLE_NAMES
    | RACE_NAMES
    | ATTR_NAMES
    | STAT_ABBREV
    | PROPER_NAMES
    | ITEM_TYPES
    | MONSTER_NAMES
    | COMMAND_NAMES
    | TERRAIN_NAMES
    | TUTORIAL_TERMS
    | LICENSE_TERMS
)


# ──── Palabras españolas que coinciden con inglés (falsos positivos) ────

SPANISH_WORDS = {
    # Artículos y determinantes
    "a",
    "de",
    "no",
    "la",
    "el",
    "un",
    "una",
    "las",
    "los",
    "su",
    "sus",
    "tu",
    "mi",
    # Verbos comunes (coinciden con inglés)
    "has",
    "es",
    "son",
    "era",
    "fue",
    "fui",
    "se",
    "me",
    "te",
    "le",
    "os",
    "he",
    "han",
    "va",
    "ve",
    "da",
    "di",
    "dio",
    "soy",
    "ves",
    "vino",
    "doy",
    "das",
    "sea",
    "seas",
    "den",
    "dan",
    "dar",
    "ver",
    "ser",
    "ir",
    "por",
    "sin",
    "mas",
    "sido",
    "estas",
    "esta",
    "este",
    "eso",
    "esa",
    "esos",
    "esas",
    # Preposiciones y conjunciones (coinciden)
    "con",
    "por",
    "para",
    "como",
    "come",  # verbo español "comer" 3ª persona
    "que",
    "donde",
    "entre",
    "sobre",
    "tras",
    "ante",
    "hacia",
    "hasta",
    # Sustantivos que parecen inglés
    "pie",
    "pan",
    "sol",
    "mar",
    "sal",
    "red",
    "don",
    "fin",
    "vez",
    "uso",
    "arte",
    "calle",
    "carta",
    "caso",
    "clase",
    "color",
    "costa",
    "crisis",
    "error",
    "falta",
    "fama",
    "fase",
    "gas",
    "golpe",
    "gota",
    "grupo",
    "idea",
    "isla",
    "lista",
    "lugar",
    "marca",
    "masa",
    "meta",
    "miedo",
    "modo",
    "monte",
    "museo",
    "nada",
    "nadie",
    "nivel",
    "nombre",
    "nota",
    "obra",
    "orden",
    "origen",
    "papel",
    "parte",
    "paso",
    "plano",
    "planta",
    "plaza",
    "pobre",
    "poca",
    "poco",
    "poder",
    "posible",
    "problema",
    "punto",
    "razon",
    "real",
    "resto",
    "rey",
    "risa",
    "ritmo",
    "roca",
    "ruina",
    "sabio",
    "salto",
    "sangre",
    "secreto",
    "sector",
    "selva",
    "si",
    "siglo",
    "silla",
    "simple",
    "sistema",
    "sitio",
    "solo",
    "sombra",
    "sonido",
    "suave",
    "subir",
    "sucio",
    "suelo",
    "suerte",
    "superior",
    "sur",
    "taza",
    "taza",
    "tema",
    "tipo",
    "todo",
    "triste",
    "uso",
    "valor",
    "vida",
}

# Palabras de marcado técnico UI (coinciden con inglés)
TECH_UI_WORDS = {
    "menu",
    "option",
    "options",
    "selection",
    "version",
    "info",
    "information",
    "select",
    "choose",
    "press",
    "hit",
    "enter",
    "return",
    "continue",
    "help",
    "save",
    "quit",
    "exit",
    "cancel",
    "abort",
    "yes",
    "ok",
    "okay",
    "retry",
    "skip",
}


# ──── Palabras inglesas que indican falta de traducción ────

ENGLISH_WORDS = {
    # Artículos y determinantes
    "the",
    "this",
    "that",
    "these",
    "those",
    "your",
    "my",
    "his",
    "her",
    "its",
    "our",
    "their",
    # Pronombres
    "you",
    "he",
    "she",
    "it",
    "we",
    "they",
    "me",
    "him",
    "us",
    "them",
    # Verbos "to be"
    "are",
    "were",
    "been",
    "being",
    "am",
    "is",
    "was",
    # Verbos auxiliares
    "have",
    "has",
    "had",
    "having",
    "does",
    "did",
    "done",
    "doing",
    "can",
    "could",
    "will",
    "would",
    "shall",
    "should",
    "may",
    "might",
    "must",
    "need",
    "needs",
    "needed",
    # Conjunciones
    "and",
    "or",
    "but",
    "nor",
    "yet",
    "for",
    "so",
    "because",
    "since",
    "unless",
    "although",
    "while",
    "once",
    "whether",
    # Preposiciones
    "with",
    "without",
    "within",
    "from",
    "into",
    "onto",
    "upon",
    "about",
    "above",
    "across",
    "after",
    "against",
    "along",
    "among",
    "around",
    "at",
    "before",
    "behind",
    "below",
    "beneath",
    "beside",
    "between",
    "beyond",
    "by",
    "down",
    "during",
    "except",
    "inside",
    "of",
    "off",
    "out",
    "outside",
    "over",
    "past",
    "through",
    "to",
    "toward",
    "towards",
    "under",
    "until",
    "up",
    "onto",
    # Cuantificadores
    "many",
    "much",
    "more",
    "most",
    "some",
    "any",
    "each",
    "every",
    "both",
    "few",
    "several",
    "other",
    "another",
    "such",
    "same",
    "different",
    "enough",
    "all",
    "no",
    "none",
    "nothing",
    # Adjetivos comunes
    "good",
    "bad",
    "new",
    "old",
    "great",
    "small",
    "large",
    "high",
    "low",
    "long",
    "short",
    "first",
    "last",
    "next",
    "right",
    "wrong",
    "left",
    "top",
    "bottom",
    "middle",
    "only",
    "very",
    "too",
    "just",
    "now",
    "then",
    "here",
    "there",
    "always",
    "never",
    "back",
    "forward",
    "away",
    # Direcciones
    "north",
    "south",
    "east",
    "west",
    "northern",
    "southern",
    "eastern",
    "western",
    # Verbos de acción comunes
    "pick",
    "picks",
    "picked",
    "choose",
    "chooses",
    "chose",
    "chosen",
    "press",
    "presses",
    "pressed",
    "hit",
    "hits",
    "hit",
    "use",
    "uses",
    "used",
    "using",
    "get",
    "gets",
    "got",
    "gotten",
    "take",
    "takes",
    "took",
    "taken",
    "make",
    "makes",
    "made",
    "see",
    "sees",
    "saw",
    "seen",
    "know",
    "knows",
    "knew",
    "known",
    "want",
    "wants",
    "wanted",
    "need",
    "needs",
    "needed",
    "try",
    "tries",
    "tried",
    "find",
    "finds",
    "found",
    "give",
    "gives",
    "gave",
    "given",
    "kill",
    "kills",
    "killed",
    "move",
    "moves",
    "moved",
    "moving",
    "open",
    "opens",
    "opened",
    "close",
    "closes",
    "closed",
    "drop",
    "drops",
    "dropped",
    "throw",
    "throws",
    "threw",
    "thrown",
    "read",
    "reads",
    "read",
    "wear",
    "wears",
    "wore",
    "worn",
    "remove",
    "removes",
    "removed",
    "apply",
    "applies",
    "applied",
    "call",
    "calls",
    "called",
    "name",
    "names",
    "named",
    "start",
    "starts",
    "started",
    "play",
    "plays",
    "played",
    "wait",
    "waits",
    "waited",
    "go",
    "goes",
    "went",
    "gone",
    "come",
    "comes",
    "came",
    "look",
    "looks",
    "looked",
    "search",
    "searches",
    "searched",
    "walk",
    "walks",
    "walked",
    "run",
    "runs",
    "ran",
    "eat",
    "eats",
    "ate",
    "eaten",
    "drink",
    "drinks",
    "drank",
    "drunk",
    "put",
    "puts",
    "put",
    "set",
    "sets",
    "set",
    "ask",
    "asks",
    "asked",
    "answer",
    "answers",
    "answered",
    "tell",
    "tells",
    "told",
    "say",
    "says",
    "said",
    "think",
    "thinks",
    "thought",
    "feel",
    "feels",
    "felt",
    "keep",
    "keeps",
    "kept",
    "hold",
    "holds",
    "held",
    "let",
    "lets",
    "let",
    "live",
    "lives",
    "lived",
    "mean",
    "means",
    "meant",
    "meet",
    "meets",
    "met",
    "pay",
    "pays",
    "paid",
    "show",
    "shows",
    "showed",
    "shown",
    "stand",
    "stands",
    "stood",
    "bring",
    "brings",
    "brought",
    "buy",
    "buys",
    "bought",
    "cut",
    "cuts",
    "cut",
    "fight",
    "fights",
    "fought",
    "fly",
    "flies",
    "flew",
    "flown",
    "forget",
    "forgets",
    "forgot",
    "forgotten",
    "grow",
    "grows",
    "grew",
    "grown",
    "hide",
    "hides",
    "hid",
    "hidden",
    "lead",
    "leads",
    "led",
    "learn",
    "learns",
    "learned",
    "learnt",
    "lose",
    "loses",
    "lost",
    "send",
    "sends",
    "sent",
    "sing",
    "sings",
    "sang",
    "sung",
    "sleep",
    "sleeps",
    "slept",
    "speak",
    "speaks",
    "spoke",
    "spoken",
    "spend",
    "spends",
    "spent",
    "swim",
    "swims",
    "swam",
    "swum",
    "teach",
    "teaches",
    "taught",
    "understand",
    "understands",
    "understood",
    "write",
    "writes",
    "wrote",
    "written",
    "fumble",
    "fumbles",
    "fumbled",
    "hunger",
    "hungers",
    "hungered",
    "hungry",
    "fall",
    "falls",
    "fell",
    "fallen",
    "resist",
    "resists",
    "resisted",
}


import re


def is_english_word(word):
    """Comprueba si una palabra es inglesa (no española ni término del juego)."""
    w = word.lower().strip(".,!?;:()[]{}'\"")
    if not w or len(w) < 2:
        return False
    if w in GAME_TERMS or w in SPANISH_WORDS or w in TECH_UI_WORDS:
        return False
    return w in ENGLISH_WORDS


def count_english_words(text, min_english=3):
    """
    Cuenta palabras inglesas en un texto.
    Devuelve (tiene_ingles, palabras_encontradas, total_palabras_ingles).
    """
    words = re.findall(r"\b[a-zA-ZáéíóúüñÁÉÍÓÚÜÑ]+\b", text.lower())
    english = []
    for w in words:
        if is_english_word(w):
            english.append(w)
    return len(english) >= min_english, english[:10], len(english)
